using System.Text;

namespace CrestCore.Generator;

/// Emits `crest_contracts.h`: the schema fingerprint and every root's wire tags
/// for C and C++ callers of `crest_app.h`.
internal static class CHeaderEmitter {
    #region Actions - Emitting

    public static string Emit(ContractSchema schema) {
        ArgumentNullException.ThrowIfNull(schema);
        var code = new StringBuilder();
        code.Append("""
            /* <auto-generated/>
             * Generated by CrestCore/tools/CrestCore.Generator from the C# contract records. Do not edit.
             * A union on the wire is its root's tag (a LEB128 varint) followed by the type's fields.
             */
            #ifndef CREST_CONTRACTS_H
            #define CREST_CONTRACTS_H

            /* SHA-256 of the canonical contract schema; pass it to crest_app_create. */
            #define CREST_CONTRACTS_FINGERPRINT_LENGTH 32u

            """);
        code.Append("#define CREST_CONTRACTS_FINGERPRINT { ");
        code.Append(string.Join(", ", schema.Fingerprint.Select(value => $"0x{value:x2}"))).Append(" }\n");
        foreach (var root in Enum.GetValues<ContractRoot>()) {
            code.Append('\n').Append($"/* {root} tags */\n");
            string prefix = $"CREST_{Naming.UpperSnake(root.ToString())}_";
            foreach (var member in schema.Members(root))
                code.Append($"#define {prefix}{Naming.UpperSnake(member.Name)} {member.Tag}u\n");
        }
        code.Append("\n#endif /* CREST_CONTRACTS_H */\n");
        return code.ToString();
    }

    #endregion
}
