using System.Text;

namespace CrestCore.Generator;

/// Emits `crest_engine_contract.h`: the engine contract's types and wire codec
/// in portable C++20, for an engine binding written in C++. It uses the
/// standard library alone and never throws, so Chromium, which builds without
/// exceptions, and a binding on another platform can both include it.
///
/// A record is an aggregate struct with snake_case fields, a union is a
/// `std::variant` whose index is its wire tag, and a fixed set or an enum is an
/// `enum class`: C++ reads nothing but a member's tag.
internal static class CppCodecEmitter {
    #region Static Variables

    private const string Namespace = "crest::engine";

    #endregion

    #region Actions - Emitting

    public static string Emit(ContractSchema engine) {
        ArgumentNullException.ThrowIfNull(engine);
        var code = new StringBuilder();
        code.Append("""
            // <auto-generated/>
            // Generated by CrestCore/tools/CrestCore.Generator from the C# contract records. Do not edit.
            //
            // The engine contract of crest_engine.h in C++: the commands the core
            // issues to an engine binding, the events a binding reports, and the
            // registration it hands the core, with their positional wire codec.
            // Lengths, counts, tags and enums are LEB128 varints; numbers are
            // fixed-width little-endian; a GUID is 16 bytes in RFC 4122 order; a
            // string is its UTF-8 length and bytes; an optional is a presence byte;
            // a union is its root's tag, the member's index, followed by its fields.
            #ifndef CREST_ENGINE_CONTRACT_H_
            #define CREST_ENGINE_CONTRACT_H_

            #include <array>
            #include <bit>
            #include <cstddef>
            #include <cstdint>
            #include <cstring>
            #include <limits>
            #include <optional>
            #include <string>
            #include <type_traits>
            #include <utility>
            #include <variant>
            #include <vector>
            """);
        code.Append($"\n\nnamespace {Namespace} {{\n\n");
        code.Append("// SHA-256 of the engine contract alone. A binding registers with it, so the\n");
        code.Append("// core refuses an engine built against any other contract.\n");
        code.Append("inline constexpr std::array<uint8_t, 32> kFingerprint = {\n    ");
        code.Append(string.Join(", ", engine.Fingerprint.Select(value => $"0x{value:x2}"))).Append("};\n\n");
        code.Append(Wire);
        foreach (var item in engine.Enums) EmitEnum(code, item);
        foreach (var set in engine.Sets.Where(set => !set.IsOpen)) EmitSet(code, set);
        foreach (var record in Ordered(engine)) EmitRecord(code, record);
        foreach (var root in ContractRoot.All.Where(root => root.IsEngine)) EmitRoot(code, engine, root);
        code.Append(Messages).Append('\n');
        code.Append($"}}  // namespace {Namespace}\n\n#endif  // CREST_ENGINE_CONTRACT_H_\n");
        return code.ToString();
    }

    /// Every record, each after the records its fields hold, so each struct is
    /// complete where another names it.
    private static IReadOnlyList<ContractRecord> Ordered(ContractSchema engine) {
        var ordered = new List<ContractRecord>();
        var placed = new HashSet<Type>();
        void Place(ContractRecord record, HashSet<Type> visiting) {
            if (placed.Contains(record.Type)) return;
            if (!visiting.Add(record.Type))
                throw new ContractSchemaException($"{record.Name}: an engine record cannot hold itself; C++ needs each struct complete.");
            if (record.Resolved.Count > 0)
                throw new ContractSchemaException($"{record.Name}: an engine record cannot carry [Resolved] values, which only the core computes.");
            foreach (var field in record.Fields)
                foreach (var held in HeldRecords(field.Type))
                    Place(engine.Records.Single(candidate => candidate.Type == held), visiting);
            placed.Add(record.Type);
            ordered.Add(record);
        }
        foreach (var record in engine.Records) Place(record, []);
        return ordered;
    }

    private static IEnumerable<Type> HeldRecords(FieldType type) => type switch {
        RecordField record => [record.Type],
        ListField list => HeldRecords(list.Element),
        OptionalField optional => HeldRecords(optional.Value),
        RootField => throw new ContractSchemaException("An engine record cannot hold a union; C++ has no member of it."),
        _ => []
    };

    private static void EmitEnum(StringBuilder code, ContractEnum item) {
        code.Append($"enum class {item.Name} : uint32_t {{\n");
        foreach (var (name, value) in item.Members) code.Append($"  k{name} = {value},\n");
        code.Append("};\n");
        if (item.IsFlags) {
            int mask = item.Members.Aggregate(0, (all, member) => all | member.Value);
            code.Append($"inline constexpr uint32_t k{item.Name}Mask = {mask};\n");
            code.Append($"constexpr {item.Name} operator|({item.Name} lhs, {item.Name} rhs) {{\n");
            code.Append($"  return static_cast<{item.Name}>(static_cast<uint32_t>(lhs) | static_cast<uint32_t>(rhs));\n}}\n");
            code.Append($"constexpr {item.Name}& operator|=({item.Name}& lhs, {item.Name} rhs) {{ return lhs = lhs | rhs; }}\n");
            code.Append($"constexpr bool Has({item.Name} value, {item.Name} flag) {{\n");
            code.Append("  return (static_cast<uint32_t>(value) & static_cast<uint32_t>(flag)) != 0;\n}\n");
            code.Append($"inline void Write(WireWriter& writer, {item.Name} value) {{ writer.WriteVarint(static_cast<uint32_t>(value)); }}\n");
            code.Append($"inline bool Read(WireReader& reader, {item.Name}& value) {{\n");
            code.Append($"  value = static_cast<{item.Name}>(reader.ReadFlags(k{item.Name}Mask));\n  return reader.ok();\n}}\n\n");
            return;
        }
        code.Append($"inline void Write(WireWriter& writer, {item.Name} value) {{ writer.WriteVarint(static_cast<uint32_t>(value)); }}\n");
        code.Append($"inline bool Read(WireReader& reader, {item.Name}& value) {{\n");
        code.Append($"  value = static_cast<{item.Name}>(reader.ReadEnum({item.Members.Count}));\n  return reader.ok();\n}}\n\n");
    }

    /// A fixed set's members, by their wire tags. Its data stays with the
    /// platforms that read it.
    private static void EmitSet(StringBuilder code, ContractSet set) {
        code.Append($"enum class {set.Name} : uint32_t {{\n");
        foreach (var member in set.Members) code.Append($"  k{member.Name} = {member.Tag},\n");
        code.Append("};\n");
        code.Append($"inline void Write(WireWriter& writer, {set.Name} value) {{ writer.WriteVarint(static_cast<uint32_t>(value)); }}\n");
        code.Append($"inline bool Read(WireReader& reader, {set.Name}& value) {{\n");
        code.Append($"  value = static_cast<{set.Name}>(reader.ReadEnum({set.Members.Count}));\n  return reader.ok();\n}}\n\n");
    }

    private static void EmitRecord(StringBuilder code, ContractRecord record) {
        code.Append($"struct {record.Name} {{\n");
        foreach (var field in record.Fields)
            code.Append($"  {TypeName(field.Type)} {Member(field.Name)}{DefaultValue(field.Type)};\n");
        code.Append($"\n  friend bool operator==(const {record.Name}&, const {record.Name}&) = default;\n}};\n");
        code.Append($"inline void Write(WireWriter& writer, const {record.Name}& value) {{\n");
        if (record.Fields.Count == 0) code.Append("  (void)writer;\n  (void)value;\n");
        foreach (var field in record.Fields) code.Append($"  Write(writer, value.{Member(field.Name)});\n");
        code.Append("}\n");
        code.Append($"inline bool Read(WireReader& reader, {record.Name}& value) {{\n");
        if (record.Fields.Count == 0) code.Append("  (void)value;\n  return reader.ok();\n}\n\n");
        else code.Append("  return ").Append(string.Join("\n      && ", record.Fields.Select(field => $"Read(reader, value.{Member(field.Name)})")))
                .Append(";\n}\n\n");
    }

    /// A root's members as one variant whose index is the wire tag.
    private static void EmitRoot(StringBuilder code, ContractSchema engine, ContractRoot root) {
        var members = engine.Members(root);
        if (members.Count == 0) return;
        code.Append($"using {root.Name} = std::variant<{string.Join(", ", members.Select(member => member.Name))}>;\n");
        if (root.HasAnswer) {
            // What each message answers with, which the binding encodes on its own.
            code.Append($"template <typename T>\nstruct {root.Name}Answer;\n");
            foreach (var member in members)
                code.Append($"template <>\nstruct {root.Name}Answer<{member.Name}> {{\n  using Type = {TypeName(member.Answer!)};\n}};\n");
        }
        code.Append($"inline void Write(WireWriter& writer, const {root.Name}& value) {{\n");
        code.Append("  writer.WriteVarint(value.index());\n");
        code.Append("  std::visit([&writer](const auto& member) { Write(writer, member); }, value);\n}\n");
        code.Append($"inline bool Read(WireReader& reader, {root.Name}& value) {{\n");
        code.Append("  switch (reader.ReadTag()) {\n");
        foreach (var member in members) {
            code.Append($"    case {member.Tag}: {{\n      {member.Name} member;\n");
            code.Append("      if (!Read(reader, member)) return false;\n      value = std::move(member);\n      return true;\n    }\n");
        }
        code.Append("    default:\n      reader.Fail();\n      return false;\n  }\n}\n\n");
    }

    #endregion

    #region Actions - Fields

    private static string TypeName(FieldType type) => type switch {
        PrimitiveField { Kind: Primitive.Bool } => "bool",
        PrimitiveField { Kind: Primitive.Int } => "int32_t",
        PrimitiveField { Kind: Primitive.Long } => "int64_t",
        PrimitiveField { Kind: Primitive.ULong } => "uint64_t",
        PrimitiveField { Kind: Primitive.Double } => "double",
        PrimitiveField { Kind: Primitive.String } => "std::string",
        PrimitiveField { Kind: Primitive.Guid } => "Guid",
        PrimitiveField { Kind: Primitive.Date } => "Date",
        PrimitiveField { Kind: Primitive.Duration } => "Duration",
        PrimitiveField { Kind: Primitive.Bytes } => "Bytes",
        EnumField item => item.Type.Name,
        SetField set => set.Type.Name,
        RecordField record => record.Type.Name,
        ListField list => $"std::vector<{TypeName(list.Element)}>",
        OptionalField optional => $"std::optional<{TypeName(optional.Value)}>",
        _ => throw new ContractSchemaException($"An engine field of type {ContractSchema.Describe(type)} has no C++ spelling.")
    };

    /// Scalars start at zero and fixed sets at their first member, so a
    /// designated initializer names only the fields it sets.
    private static string DefaultValue(FieldType type) => type switch {
        PrimitiveField { Kind: Primitive.Bool } => " = false",
        PrimitiveField { Kind: Primitive.Int or Primitive.Long or Primitive.ULong or Primitive.Double } => " = 0",
        PrimitiveField { Kind: Primitive.Guid } => " = {}",
        PrimitiveField { Kind: Primitive.Date or Primitive.Duration } => " = {}",
        EnumField or SetField => " = {}",
        _ => ""
    };

    /// `PageId` becomes `page_id`, `IsPrivate` becomes `is_private`.
    private static string Member(string name) => string.Join('_', Naming.Words(name).Select(word => word.ToLowerInvariant()));

    #endregion

    #region Actions - Wire

    private const string Wire = """
        // A GUID in RFC 4122 byte order, as the wire carries it.
        using Guid = std::array<uint8_t, 16>;
        // A byte string.
        using Bytes = std::vector<uint8_t>;

        // Seconds since 1 January 2001, as the wire carries a date.
        struct Date {
          double seconds_since_2001 = 0;
          friend bool operator==(const Date&, const Date&) = default;
        };

        // Seconds, as the wire carries a duration.
        struct Duration {
          double seconds = 0;
          friend bool operator==(const Duration&, const Duration&) = default;
        };

        // Writes the positional wire format.
        class WireWriter {
         public:
          const std::vector<uint8_t>& bytes() const { return bytes_; }
          std::vector<uint8_t> Take() { return std::move(bytes_); }

          void WriteVarint(uint64_t value) {
            do {
              uint8_t next = static_cast<uint8_t>(value & 0x7f);
              value >>= 7;
              bytes_.push_back(value == 0 ? next : static_cast<uint8_t>(next | 0x80));
            } while (value != 0);
          }
          void WriteFixed(uint64_t bits, size_t width) {
            for (size_t index = 0; index < width; ++index) {
              bytes_.push_back(static_cast<uint8_t>(bits >> (8 * index)));
            }
          }
          void WriteRaw(const uint8_t* data, size_t length) { bytes_.insert(bytes_.end(), data, data + length); }

         private:
          std::vector<uint8_t> bytes_;
        };

        // Reads the positional wire format. A malformed message fails the reader,
        // and every later read answers a default value, so a caller checks `ok()`
        // once, after reading the whole message.
        class WireReader {
         public:
          WireReader(const uint8_t* data, size_t length) : data_(data), length_(data ? length : 0) {}

          bool ok() const { return !failed_; }
          bool AtEnd() const { return position_ == length_; }
          size_t remaining() const { return length_ - position_; }
          void Fail() { failed_ = true; }

          uint64_t ReadVarint() {
            uint64_t value = 0;
            for (int shift = 0; shift < 64; shift += 7) {
              const uint8_t* next = Take(1);
              if (!next) return 0;
              const uint64_t bits = *next & 0x7f;
              if (shift == 63 && bits > 1) return Failed();
              value |= bits << shift;
              if ((*next & 0x80) == 0) {
                if (*next == 0 && shift > 0) return Failed();
                return value;
              }
            }
            return Failed();
          }
          // A union's tag, a varint of at most 31 bits.
          uint32_t ReadTag() { return static_cast<uint32_t>(ReadBounded(std::numeric_limits<int32_t>::max())); }
          // A list's count; every element takes at least one byte.
          size_t ReadCount() { return static_cast<size_t>(ReadBounded(remaining())); }
          // A plain enum's value, which must be below `count`.
          uint32_t ReadEnum(uint32_t count) { return static_cast<uint32_t>(ReadBounded(count - 1)); }
          // A flags enum's value, which may set only bits in `mask`.
          uint32_t ReadFlags(uint32_t mask) {
            const uint64_t value = ReadBounded(std::numeric_limits<int32_t>::max());
            if ((value & ~static_cast<uint64_t>(mask)) != 0) return static_cast<uint32_t>(Failed());
            return static_cast<uint32_t>(value);
          }
          bool ReadFlag() {
            const uint8_t* next = Take(1);
            if (!next) return false;
            if (*next > 1) return Failed() != 0;
            return *next == 1;
          }
          uint64_t ReadFixed(size_t width) {
            const uint8_t* next = Take(width);
            uint64_t bits = 0;
            for (size_t index = 0; next && index < width; ++index) {
              bits |= static_cast<uint64_t>(next[index]) << (8 * index);
            }
            return bits;
          }
          const uint8_t* Take(size_t length) {
            if (failed_ || length > remaining()) {
              failed_ = true;
              return nullptr;
            }
            const uint8_t* start = data_ + position_;
            position_ += length;
            return start;
          }

         private:
          uint64_t ReadBounded(uint64_t maximum) {
            const uint64_t value = ReadVarint();
            return value <= maximum ? value : Failed();
          }
          uint64_t Failed() {
            failed_ = true;
            return 0;
          }

          const uint8_t* data_;
          size_t length_;
          size_t position_ = 0;
          bool failed_ = false;
        };

        // Whether `text` is well-formed UTF-8: no overlong forms, surrogates or
        // code points past U+10FFFF, as the core's strict decoder requires.
        inline bool IsUtf8(const uint8_t* text, size_t length) {
          size_t index = 0;
          while (index < length) {
            const uint8_t lead = text[index];
            size_t extra = 0;
            uint32_t point = 0;
            if (lead < 0x80) {
              ++index;
              continue;
            } else if (lead >= 0xc2 && lead <= 0xdf) {
              extra = 1;
              point = lead & 0x1f;
            } else if (lead >= 0xe0 && lead <= 0xef) {
              extra = 2;
              point = lead & 0x0f;
            } else if (lead >= 0xf0 && lead <= 0xf4) {
              extra = 3;
              point = lead & 0x07;
            } else {
              return false;
            }
            if (extra > length - index - 1) return false;
            for (size_t next = 1; next <= extra; ++next) {
              const uint8_t continuation = text[index + next];
              if ((continuation & 0xc0) != 0x80) return false;
              point = (point << 6) | (continuation & 0x3f);
            }
            if ((extra == 2 && (point < 0x800 || (point >= 0xd800 && point <= 0xdfff))) ||
                (extra == 3 && (point < 0x10000 || point > 0x10ffff))) {
              return false;
            }
            index += extra + 1;
          }
          return true;
        }

        inline void Write(WireWriter& writer, bool value) { writer.WriteFixed(value ? 1 : 0, 1); }
        inline void Write(WireWriter& writer, int32_t value) { writer.WriteFixed(static_cast<uint32_t>(value), 4); }
        inline void Write(WireWriter& writer, int64_t value) { writer.WriteFixed(static_cast<uint64_t>(value), 8); }
        inline void Write(WireWriter& writer, uint64_t value) { writer.WriteFixed(value, 8); }
        inline void Write(WireWriter& writer, double value) { writer.WriteFixed(std::bit_cast<uint64_t>(value), 8); }
        inline void Write(WireWriter& writer, Date value) { Write(writer, value.seconds_since_2001); }
        inline void Write(WireWriter& writer, Duration value) { Write(writer, value.seconds); }
        inline void Write(WireWriter& writer, const std::string& value) {
          writer.WriteVarint(value.size());
          writer.WriteRaw(reinterpret_cast<const uint8_t*>(value.data()), value.size());
        }
        inline void Write(WireWriter& writer, const Bytes& value) {
          writer.WriteVarint(value.size());
          writer.WriteRaw(value.data(), value.size());
        }
        inline void Write(WireWriter& writer, const Guid& value) { writer.WriteRaw(value.data(), value.size()); }
        template <typename T>
        void Write(WireWriter& writer, const std::optional<T>& value) {
          writer.WriteFixed(value.has_value() ? 1 : 0, 1);
          if (value) Write(writer, *value);
        }
        template <typename T>
        void Write(WireWriter& writer, const std::vector<T>& value) {
          writer.WriteVarint(value.size());
          for (const T& item : value) Write(writer, item);
        }

        inline bool Read(WireReader& reader, bool& value) {
          value = reader.ReadFlag();
          return reader.ok();
        }
        inline bool Read(WireReader& reader, int32_t& value) {
          value = static_cast<int32_t>(static_cast<uint32_t>(reader.ReadFixed(4)));
          return reader.ok();
        }
        inline bool Read(WireReader& reader, int64_t& value) {
          value = static_cast<int64_t>(reader.ReadFixed(8));
          return reader.ok();
        }
        inline bool Read(WireReader& reader, uint64_t& value) {
          value = reader.ReadFixed(8);
          return reader.ok();
        }
        inline bool Read(WireReader& reader, double& value) {
          value = std::bit_cast<double>(reader.ReadFixed(8));
          return reader.ok();
        }
        inline bool Read(WireReader& reader, Date& value) { return Read(reader, value.seconds_since_2001); }
        inline bool Read(WireReader& reader, Duration& value) { return Read(reader, value.seconds); }
        inline bool Read(WireReader& reader, std::string& value) {
          const size_t length = reader.ReadCount();
          const uint8_t* text = reader.Take(length);
          if (!text || !IsUtf8(text, length)) {
            reader.Fail();
            return false;
          }
          value.assign(reinterpret_cast<const char*>(text), length);
          return true;
        }
        inline bool Read(WireReader& reader, Bytes& value) {
          const size_t length = reader.ReadCount();
          const uint8_t* data = reader.Take(length);
          if (!data) return false;
          value.assign(data, data + length);
          return true;
        }
        inline bool Read(WireReader& reader, Guid& value) {
          const uint8_t* data = reader.Take(value.size());
          if (!data) return false;
          std::memcpy(value.data(), data, value.size());
          return true;
        }
        template <typename T>
        bool Read(WireReader& reader, std::optional<T>& value) {
          if (!reader.ReadFlag()) {
            value.reset();
            return reader.ok();
          }
          T present{};
          if (!Read(reader, present)) return false;
          value = std::move(present);
          return true;
        }
        template <typename T>
        bool Read(WireReader& reader, std::vector<T>& value) {
          const size_t count = reader.ReadCount();
          value.clear();
          for (size_t index = 0; index < count && reader.ok(); ++index) {
            T item{};
            if (!Read(reader, item)) return false;
            value.push_back(std::move(item));
          }
          return reader.ok();
        }


        """;

    private const string Messages = """
        // One whole message: a union or the registration, encoded on its own.
        template <typename T>
        std::vector<uint8_t> Encode(const T& message) {
          WireWriter writer;
          Write(writer, message);
          return writer.Take();
        }

        // One whole message decoded, or nothing when its bytes do not decode or
        // run past it.
        template <typename T>
        std::optional<T> Decode(const uint8_t* data, size_t length) {
          WireReader reader(data, length);
          T message{};
          if (!Read(reader, message) || !reader.ok() || !reader.AtEnd()) return std::nullopt;
          return message;
        }

        """;

    #endregion
}
