using System.Text;

namespace CrestCore.Generator;

/// Emits `ContractCodec`, the core's reader and writer for every contract type.
internal static class CSharpCodecEmitter {
    #region Actions - Emitting

    public static string Emit(ContractSchema schema) {
        ArgumentNullException.ThrowIfNull(schema);
        var code = new StringBuilder();
        code.Append("""
            // <auto-generated/>
            // Generated by CrestCore/tools/CrestCore.Generator from the contract records. Do not edit.
            #nullable enable

            using CrestCore.Application;
            using CrestCore.Contracts;

            namespace CrestCore.Native;

            /// <summary>
            /// The wire codec for every contract type. A union is its root's tag, the
            /// index of the type in ordinal name order, followed by the type's fields.
            /// </summary>
            public static class ContractCodec {
                /// <summary>SHA-256 of the canonical contract schema.</summary>
                public static ReadOnlySpan<byte> Fingerprint => [
            """).Append('\n');
        code.Append("        ").Append(string.Join(", ", schema.Fingerprint.Select(value => $"0x{value:x2}"))).Append('\n');
        code.Append("    ];\n");
        foreach (var root in Enum.GetValues<ContractRoot>()) EmitRoot(code, schema, root);
        EmitAnswers(code, schema);
        foreach (var record in schema.Records) EmitRecord(code, record);
        foreach (var item in schema.Enums) EmitEnum(code, item);
        foreach (var set in schema.Sets) EmitSet(code, set);
        if (schema.Sets.Count > 0) EmitTagOf(code);
        code.Append("}\n");
        return code.ToString();
    }

    private static void EmitRoot(StringBuilder code, ContractSchema schema, ContractRoot root) {
        var members = schema.Members(root);
        string type = root == ContractRoot.Query ? "object" : root.ToString();
        code.Append('\n').Append($"    public static {type} Read{root}(WireReader reader) {{\n");
        code.Append("        int tag = reader.ReadTag();\n        switch (tag) {\n");
        foreach (var member in members)
            code.Append($"            case {member.Tag}: return Read{member.Name}(reader);\n");
        code.Append($"            default: throw new WireFormatException($\"Unknown {root} tag {{tag}}.\");\n        }}\n    }}\n");

        code.Append('\n').Append($"    public static void Write{root}(WireWriter writer, {type} value) {{\n");
        code.Append("        ArgumentNullException.ThrowIfNull(writer);\n        ArgumentNullException.ThrowIfNull(value);\n");
        code.Append("        switch (value) {\n");
        foreach (var member in members) {
            code.Append($"            case {member.Name} member:\n");
            code.Append($"                writer.WriteTag({member.Tag});\n");
            code.Append($"                Write{member.Name}(writer, member);\n                break;\n");
        }
        code.Append($"            default: throw new ArgumentOutOfRangeException(nameof(value), value.GetType().Name, \"Not a contract {root}.\");\n");
        code.Append("        }\n    }\n");
    }

    /// Writes the answer to a decoded query, so each query reaches `CrestApp`
    /// through its own typed overload.
    private static void EmitAnswers(StringBuilder code, ContractSchema schema) {
        code.Append('\n').Append("    public static void WriteAnswer(WireWriter writer, CrestApp app, object query) {\n");
        code.Append("        ArgumentNullException.ThrowIfNull(app);\n        ArgumentNullException.ThrowIfNull(query);\n");
        code.Append("        switch (query) {\n");
        foreach (var member in schema.Members(ContractRoot.Query)) {
            code.Append($"            case {member.Name} question:\n");
            code.Append($"                var answer{member.Tag} = app.Query(question);\n");
            code.Append(Write(member.Answer!, $"answer{member.Tag}", "                ", $"Answer{member.Tag}"));
            code.Append("                break;\n");
        }
        code.Append("            default: throw new ArgumentOutOfRangeException(nameof(query), query.GetType().Name, \"Not a contract Query.\");\n");
        code.Append("        }\n    }\n");
    }

    private static void EmitRecord(StringBuilder code, ContractRecord record) {
        code.Append('\n').Append($"    public static {record.Name} Read{record.Name}(WireReader reader) {{\n");
        code.Append("        ArgumentNullException.ThrowIfNull(reader);\n");
        code.Append($"        return new {record.Name}(");
        code.Append(string.Join(",", record.Fields.Select(field => $"\n            {Read(field.Type)}")));
        code.Append(");\n    }\n");

        code.Append('\n').Append($"    public static void Write{record.Name}(WireWriter writer, {record.Name} value) {{\n");
        code.Append("        ArgumentNullException.ThrowIfNull(writer);\n        ArgumentNullException.ThrowIfNull(value);\n");
        foreach (var field in record.Fields) code.Append(Write(field.Type, $"value.{field.Name}", "        ", field.Name));
        code.Append("    }\n");
    }

    private static void EmitEnum(StringBuilder code, ContractEnum item) {
        string read = item.IsFlags
            ? $"reader.ReadFlags({item.Members.Aggregate(0, (mask, member) => mask | member.Value)})"
            : $"reader.ReadEnum({item.Members.Count})";
        code.Append('\n').Append($"    public static {item.Name} Read{item.Name}(WireReader reader) {{\n");
        code.Append("        ArgumentNullException.ThrowIfNull(reader);\n");
        code.Append($"        return ({item.Name}){read};\n    }}\n");
        code.Append('\n').Append($"    public static void Write{item.Name}(WireWriter writer, {item.Name} value) {{\n");
        code.Append("        ArgumentNullException.ThrowIfNull(writer);\n");
        code.Append("        writer.WriteEnum((int)value);\n    }\n");
    }

    /// A fixed set member travels as its index in the set's `All`.
    private static void EmitSet(StringBuilder code, ContractSet set) {
        code.Append('\n').Append($"    public static {set.Name} Read{set.Name}(WireReader reader) {{\n");
        code.Append("        ArgumentNullException.ThrowIfNull(reader);\n");
        code.Append($"        return {set.Name}.All[reader.ReadEnum({set.Name}.All.Count)];\n    }}\n");
        code.Append('\n').Append($"    public static void Write{set.Name}(WireWriter writer, {set.Name} value) {{\n");
        code.Append("        ArgumentNullException.ThrowIfNull(writer);\n        ArgumentNullException.ThrowIfNull(value);\n");
        code.Append($"        writer.WriteEnum(TagOf({set.Name}.All, value));\n    }}\n");
    }

    private static void EmitTagOf(StringBuilder code) => code.Append("""

            /// <summary>A fixed set member's wire tag: its index in the set's <c>All</c>.</summary>
            private static int TagOf<T>(IReadOnlyList<T> all, T value) where T : class {
                for (int tag = 0; tag < all.Count; tag++)
                    if (ReferenceEquals(all[tag], value)) return tag;
                throw new ArgumentOutOfRangeException(nameof(value), value, "Not a member of its fixed set.");
            }

        """);

    #endregion

    #region Actions - Fields

    private static string Read(FieldType type) => type switch {
        PrimitiveField primitive => $"reader.Read{Method(primitive.Kind)}()",
        EnumField item => $"Read{item.Type.Name}(reader)",
        SetField set => $"Read{set.Type.Name}(reader)",
        RecordField record => $"Read{record.Type.Name}(reader)",
        RootField root => $"Read{root.Root}(reader)",
        ListField list => $"reader.ReadList(() => {Read(list.Element)})",
        OptionalField optional => $"reader.ReadPresence() ? ({TypeName(optional)}){Read(optional.Value)} : null",
        _ => throw new ContractSchemaException($"Unknown field type {type}.")
    };

    /// Pattern variables in an `if` share the method's scope, so each carries
    /// the field's name as `scope`.
    private static string Write(FieldType type, string value, string indent, string scope) => type switch {
        PrimitiveField primitive => $"{indent}writer.Write{Method(primitive.Kind)}({value});\n",
        EnumField item => $"{indent}Write{item.Type.Name}(writer, {value});\n",
        SetField set => $"{indent}Write{set.Type.Name}(writer, {value});\n",
        RecordField record => $"{indent}Write{record.Type.Name}(writer, {value});\n",
        RootField root => $"{indent}Write{root.Root}(writer, {value});\n",
        ListField list => $"{indent}writer.WriteCount({value}.Count);\n"
            + $"{indent}foreach (var item{scope} in {value}) {{\n"
            + Write(list.Element, $"item{scope}", indent + "    ", $"{scope}Item")
            + $"{indent}}}\n",
        OptionalField optional => $"{indent}if ({value} is {{ }} present{scope}) {{\n"
            + $"{indent}    writer.WritePresence(true);\n"
            + Write(optional.Value, $"present{scope}", indent + "    ", $"{scope}Value")
            + $"{indent}}} else {{\n{indent}    writer.WritePresence(false);\n{indent}}}\n",
        _ => throw new ContractSchemaException($"Unknown field type {type}.")
    };

    private static string Method(Primitive kind) => kind switch {
        Primitive.Int => "Int32",
        Primitive.Long => "Int64",
        _ => kind.ToString()
    };

    private static string TypeName(FieldType type) => type switch {
        PrimitiveField { Kind: Primitive.Bool } => "bool",
        PrimitiveField { Kind: Primitive.Int } => "int",
        PrimitiveField { Kind: Primitive.Long } => "long",
        PrimitiveField { Kind: Primitive.Double } => "double",
        PrimitiveField { Kind: Primitive.String } => "string",
        PrimitiveField { Kind: Primitive.Guid } => "Guid",
        PrimitiveField { Kind: Primitive.Date } => "DateTimeOffset",
        PrimitiveField { Kind: Primitive.Duration } => "TimeSpan",
        EnumField item => item.Type.Name,
        SetField set => set.Type.Name,
        RecordField record => record.Type.Name,
        RootField root => root.Root.ToString(),
        ListField list => $"IReadOnlyList<{TypeName(list.Element)}>",
        OptionalField optional => $"{TypeName(optional.Value)}?",
        _ => throw new ContractSchemaException($"Unknown field type {type}.")
    };

    #endregion
}
