using System.Text;

namespace CrestCore.Generator;

/// Emits the Swift read model and its codec. Records become structs, enums
/// become `Int` enums or option sets, intents and queries conform to the
/// `Intent` and `Query` protocols, and changes and rejections become the cases
/// of `Change` and `Rejection`.
internal static class SwiftEmitter {
    #region Variables

    private const string Header = """
        // <auto-generated/>
        // Generated by CrestCore/tools/CrestCore.Generator from the C# contract records. Do not edit.

        import Foundation

        """;

    #endregion

    #region Actions - Contracts

    public static string EmitContracts(ContractSchema schema) {
        ArgumentNullException.ThrowIfNull(schema);
        var equatable = EquatableRecords(schema);
        var code = new StringBuilder(Header);
        code.Append("""

            // MARK: - Roots

            /// A request to change the core's state, sent with `CrestCore.send`.
            protocol Intent: Sendable {
                func encodeIntent(into writer: inout WireWriter)
            }

            /// A question the core answers without changing state, asked with `CrestCore.query`.
            protocol Query: Sendable {
                associatedtype Answer: Sendable
                func encodeQuery(into writer: inout WireWriter)
                static func decodeAnswer(from reader: inout WireReader) throws(WireError) -> Answer
            }

            """);
        EmitUnion(code, schema, ContractRoot.Change, "/// Everything an intent can change. `CoreState.apply` keeps the read model current.", equatable, "Sendable");
        EmitUnion(code, schema, ContractRoot.Rejection, "/// The rule that refused an intent or a query.", equatable, "Error, Sendable");
        code.Append("""

            extension CoreState {
                /// Applies one change through the hand-written applier for its type.
                func apply(_ change: Change) {
                    switch change {

            """);
        foreach (var member in schema.Members(ContractRoot.Change))
            code.Append($"        case .{Naming.SwiftMember(member.Name)}(let change): apply(change)\n");
        code.Append("        }\n    }\n}\n");

        var roots = new Dictionary<Type, (ContractRoot Root, ContractMember Member)>();
        foreach (var root in Enum.GetValues<ContractRoot>())
            foreach (var member in schema.Members(root)) roots[member.Record.Type] = (root, member);
        code.Append("\n// MARK: - Records\n");
        foreach (var record in schema.Records) {
            var conformances = new List<string>();
            if (roots.TryGetValue(record.Type, out var owner) && owner.Root is ContractRoot.Intent or ContractRoot.Query)
                conformances.Add(owner.Root.ToString());
            if (equatable.Contains(record.Type)) conformances.Add("Equatable");
            conformances.Add("Sendable");
            if (record.Fields.Any(field => field.Name == "Id")) conformances.Add("Identifiable");
            code.Append('\n').Append($"struct {record.Name}: {string.Join(", ", conformances)} {{\n");
            if (owner.Root == ContractRoot.Query && roots.ContainsKey(record.Type))
                code.Append($"    typealias Answer = {TypeName(owner.Member.Answer!)}\n\n");
            foreach (var field in record.Fields)
                code.Append($"    let {Naming.SwiftIdentifier(Naming.SwiftMember(field.Name))}: {TypeName(field.Type)}\n");
            code.Append("}\n");
        }

        code.Append("\n// MARK: - Enums\n");
        foreach (var item in schema.Enums) {
            code.Append('\n');
            if (item.IsFlags) {
                code.Append($"struct {item.Name}: OptionSet, Sendable {{\n    let rawValue: Int\n");
                foreach (var member in item.Members.Where(member => member.Value != 0))
                    code.Append($"    static let {Naming.SwiftIdentifier(Naming.SwiftMember(member.Key))} = {item.Name}(rawValue: {member.Value})\n");
            } else {
                code.Append($"enum {item.Name}: Int, CaseIterable, Sendable {{\n");
                foreach (var member in item.Members)
                    code.Append($"    case {Naming.SwiftIdentifier(Naming.SwiftMember(member.Key))} = {member.Value}\n");
            }
            code.Append("}\n");
        }
        return code.ToString();
    }

    private static void EmitUnion(StringBuilder code, ContractSchema schema, ContractRoot root, string documentation,
        HashSet<Type> equatable, string conformances) {
        var members = schema.Members(root);
        bool isEquatable = members.All(member => equatable.Contains(member.Record.Type));
        code.Append('\n').Append(documentation).Append('\n');
        code.Append($"enum {root}: {(isEquatable ? "Equatable, " : "")}{conformances} {{\n");
        foreach (var member in members) code.Append($"    case {Naming.SwiftMember(member.Name)}({member.Name})\n");
        code.Append("}\n");
    }

    /// A record is Equatable unless it holds, directly or through its fields,
    /// an intent or a query existential.
    private static HashSet<Type> EquatableRecords(ContractSchema schema) {
        var records = schema.Records.ToDictionary(record => record.Type);
        var excluded = new HashSet<Type>();
        bool changed = true;
        while (changed) {
            changed = false;
            foreach (var record in records.Values.Where(record => !excluded.Contains(record.Type)))
                if (record.Fields.Any(field => !IsEquatable(field.Type, excluded, schema))) changed |= excluded.Add(record.Type);
        }
        return [.. records.Keys.Where(type => !excluded.Contains(type))];
    }

    private static bool IsEquatable(FieldType type, HashSet<Type> excluded, ContractSchema schema) => type switch {
        RecordField record => !excluded.Contains(record.Type),
        RootField { Root: ContractRoot.Intent or ContractRoot.Query } => false,
        RootField root => schema.Members(root.Root).All(member => !excluded.Contains(member.Record.Type)),
        ListField list => IsEquatable(list.Element, excluded, schema),
        OptionalField optional => IsEquatable(optional.Value, excluded, schema),
        _ => true
    };

    #endregion

    #region Actions - Codec

    public static string EmitCodec(ContractSchema schema) {
        ArgumentNullException.ThrowIfNull(schema);
        var code = new StringBuilder(Header);
        code.Append('\n').Append("/// The wire codec's schema identity and the unions Swift decodes.\n");
        code.Append("enum CoreCodec {\n");
        code.Append("    /// SHA-256 of the canonical contract schema. The core refuses any other.\n");
        code.Append("    static let fingerprint: [UInt8] = [\n        ");
        code.Append(string.Join(", ", schema.Fingerprint.Select(value => $"0x{value:x2}"))).Append("\n    ]\n");
        foreach (var root in new[] { ContractRoot.Intent, ContractRoot.Query }) {
            code.Append('\n').Append($"    static func decode{root}(from reader: inout WireReader) throws(WireError) -> any {root} {{\n");
            code.Append("        let tag = try reader.readTag()\n        switch tag {\n");
            foreach (var member in schema.Members(root))
                code.Append($"        case {member.Tag}: return try {member.Name}(from: &reader)\n");
            code.Append($"        default: throw WireError.malformed(\"Unknown {root} tag \\(tag)\")\n        }}\n    }}\n");
        }
        code.Append("}\n");

        foreach (var root in new[] { ContractRoot.Change, ContractRoot.Rejection }) {
            var members = schema.Members(root);
            code.Append('\n').Append($"extension {root} {{\n");
            code.Append("    init(from reader: inout WireReader) throws(WireError) {\n");
            code.Append("        let tag = try reader.readTag()\n        switch tag {\n");
            foreach (var member in members)
                code.Append($"        case {member.Tag}: self = .{Naming.SwiftMember(member.Name)}(try {member.Name}(from: &reader))\n");
            code.Append($"        default: throw WireError.malformed(\"Unknown {root} tag \\(tag)\")\n        }}\n    }}\n\n");
            code.Append("    func encode(into writer: inout WireWriter) {\n        switch self {\n");
            foreach (var member in members) {
                code.Append($"        case .{Naming.SwiftMember(member.Name)}(let value):\n");
                code.Append($"            writer.writeTag({member.Tag})\n            value.encode(into: &writer)\n");
            }
            code.Append("        }\n    }\n}\n");
        }

        var tags = new Dictionary<Type, (ContractRoot Root, ContractMember Member)>();
        foreach (var root in new[] { ContractRoot.Intent, ContractRoot.Query })
            foreach (var member in schema.Members(root)) tags[member.Record.Type] = (root, member);
        foreach (var record in schema.Records) {
            code.Append('\n').Append($"extension {record.Name} {{\n");
            code.Append("    init(from reader: inout WireReader) throws(WireError) {\n");
            var lines = new List<string>();
            foreach (var field in record.Fields) Decode(field.Type, Local(field.Name), lines, "        ");
            foreach (var line in lines) code.Append(line).Append('\n');
            code.Append("        self.init(");
            code.Append(string.Join(", ", record.Fields.Select(field => $"{Naming.SwiftMember(field.Name)}: {Local(field.Name)}")));
            code.Append(")\n    }\n\n");
            code.Append("    func encode(into writer: inout WireWriter) {\n");
            foreach (var field in record.Fields)
                code.Append(Encode(field.Type, Naming.SwiftIdentifier(Naming.SwiftMember(field.Name)), "        ", 0));
            code.Append("    }\n");
            if (tags.TryGetValue(record.Type, out var owner)) {
                code.Append('\n').Append($"    func encode{owner.Root}(into writer: inout WireWriter) {{\n");
                code.Append($"        writer.writeTag({owner.Member.Tag})\n        encode(into: &writer)\n    }}\n");
                if (owner.Root == ContractRoot.Query) {
                    var answer = new List<string>();
                    Decode(owner.Member.Answer!, "answer", answer, "        ");
                    code.Append('\n').Append($"    static func decodeAnswer(from reader: inout WireReader) throws(WireError) -> {TypeName(owner.Member.Answer!)} {{\n");
                    foreach (var line in answer) code.Append(line).Append('\n');
                    code.Append("        return answer\n    }\n");
                }
            }
            code.Append("}\n");
        }

        foreach (var item in schema.Enums) {
            code.Append('\n').Append($"extension {item.Name} {{\n");
            code.Append("    init(from reader: inout WireReader) throws(WireError) {\n");
            code.Append("        let rawValue = try reader.readEnum()\n");
            if (item.IsFlags) {
                int mask = item.Members.Aggregate(0, (bits, member) => bits | member.Value);
                code.Append($"        guard rawValue & ~{mask} == 0 else {{ throw WireError.malformed(\"Unknown {item.Name} \\(rawValue)\") }}\n");
                code.Append("        self.init(rawValue: rawValue)\n");
            } else {
                code.Append($"        guard let value = {item.Name}(rawValue: rawValue) else {{\n");
                code.Append($"            throw WireError.malformed(\"Unknown {item.Name} \\(rawValue)\")\n        }}\n");
                code.Append("        self = value\n");
            }
            code.Append("    }\n\n    func encode(into writer: inout WireWriter) {\n        writer.writeEnum(rawValue)\n    }\n}\n");
        }
        return code.ToString();
    }

    #endregion

    #region Actions - Fields

    private static string Local(string name) => Naming.SwiftIdentifier(Naming.SwiftMember(name));

    /// Appends statements that declare `name` with the decoded value.
    private static void Decode(FieldType type, string name, List<string> lines, string indent) {
        string plain = name.Trim('`');
        switch (type) {
            case PrimitiveField primitive:
                lines.Add($"{indent}let {name} = try reader.read{Method(primitive.Kind)}()");
                break;
            case EnumField or RecordField:
                lines.Add($"{indent}let {name} = try {TypeName(type)}(from: &reader)");
                break;
            case RootField { Root: ContractRoot.Intent or ContractRoot.Query } root:
                lines.Add($"{indent}let {name} = try CoreCodec.decode{root.Root}(from: &reader)");
                break;
            case RootField root:
                lines.Add($"{indent}let {name} = try {root.Root}(from: &reader)");
                break;
            case ListField list:
                lines.Add($"{indent}let {plain}Count = try reader.readCount()");
                lines.Add($"{indent}var {name}: {TypeName(list)} = []");
                lines.Add($"{indent}{name}.reserveCapacity({plain}Count)");
                lines.Add($"{indent}for _ in 0..<{plain}Count {{");
                Decode(list.Element, $"{plain}Element", lines, indent + "    ");
                lines.Add($"{indent}    {name}.append({plain}Element)");
                lines.Add($"{indent}}}");
                break;
            case OptionalField optional:
                lines.Add($"{indent}let {name}: {TypeName(optional)}");
                lines.Add($"{indent}if try reader.readPresence() {{");
                Decode(optional.Value, $"{plain}Value", lines, indent + "    ");
                lines.Add($"{indent}    {name} = {plain}Value");
                lines.Add($"{indent}}} else {{");
                lines.Add($"{indent}    {name} = nil");
                lines.Add($"{indent}}}");
                break;
            default:
                throw new ContractSchemaException($"Unknown field type {type}.");
        }
    }

    private static string Encode(FieldType type, string value, string indent, int depth) => type switch {
        PrimitiveField primitive => $"{indent}writer.write{Method(primitive.Kind)}({value})\n",
        RootField { Root: ContractRoot.Intent or ContractRoot.Query } root => $"{indent}{value}.encode{root.Root}(into: &writer)\n",
        EnumField or RecordField or RootField => $"{indent}{value}.encode(into: &writer)\n",
        ListField list => $"{indent}writer.writeCount({value}.count)\n"
            + $"{indent}for element{depth} in {value} {{\n"
            + Encode(list.Element, $"element{depth}", indent + "    ", depth + 1)
            + $"{indent}}}\n",
        OptionalField optional => $"{indent}if let present{depth} = {value} {{\n"
            + $"{indent}    writer.writePresence(true)\n"
            + Encode(optional.Value, $"present{depth}", indent + "    ", depth + 1)
            + $"{indent}}} else {{\n{indent}    writer.writePresence(false)\n{indent}}}\n",
        _ => throw new ContractSchemaException($"Unknown field type {type}.")
    };

    private static string Method(Primitive kind) => kind switch {
        Primitive.Bool => "Bool",
        Primitive.Int => "Int",
        Primitive.Long => "Int64",
        Primitive.Double => "Double",
        Primitive.String => "String",
        Primitive.Guid => "UUID",
        Primitive.Date => "Date",
        Primitive.Duration => "TimeInterval",
        _ => throw new ContractSchemaException($"Unknown primitive {kind}.")
    };

    private static string TypeName(FieldType type) => type switch {
        PrimitiveField primitive => Method(primitive.Kind),
        EnumField item => item.Type.Name,
        RecordField record => record.Type.Name,
        RootField { Root: ContractRoot.Intent or ContractRoot.Query } root => $"any {root.Root}",
        RootField root => root.Root.ToString(),
        ListField list => $"[{TypeName(list.Element)}]",
        OptionalField { Value: RootField { Root: ContractRoot.Intent or ContractRoot.Query } } optional => $"({TypeName(optional.Value)})?",
        OptionalField optional => $"{TypeName(optional.Value)}?",
        _ => throw new ContractSchemaException($"Unknown field type {type}.")
    };

    #endregion
}
