using System.Globalization;
using System.Text;

namespace CrestCore.Generator;

/// Emits the Swift read model and its codec. Records become structs, enums
/// become `Int` enums or option sets, fixed sets become structs of `static let`
/// members, intents and queries conform to the
/// `Intent` and `Query` protocols, and changes and rejections become the cases
/// of `Change` and `Rejection`.
internal static class SwiftEmitter {
    #region Variables

    private const string Header = """
        // <auto-generated/>
        // Generated by CrestCore/tools/CrestCore.Generator from the C# contract records. Do not edit.

        import Foundation

        """;

    #endregion

    #region Actions - Contracts

    public static string EmitContracts(ContractSchema schema) {
        ArgumentNullException.ThrowIfNull(schema);
        var equatable = EquatableRecords(schema);
        var code = new StringBuilder(Header);
        code.Append("""

            // MARK: - Roots

            /// A request to change the core's state, sent with `CrestCore.send`.
            protocol Intent: Sendable {
                func encodeIntent(into writer: inout WireWriter)
            }

            /// A question the core answers without changing state, asked with `CrestCore.query`.
            protocol Query: Sendable {
                associatedtype Answer: Sendable
                func encodeQuery(into writer: inout WireWriter)
                static func decodeAnswer(from reader: inout WireReader) throws(WireError) -> Answer
            }

            """);
        EmitUnion(code, schema, ContractRoot.Change, "/// Everything an intent can change. `CoreState.apply` keeps the read model current.", equatable, "Sendable");
        EmitUnion(code, schema, ContractRoot.Rejection, "/// The rule that refused an intent or a query.", equatable, "Error, Sendable");
        code.Append("""

            extension CoreState {
                /// Applies one change through the hand-written applier for its type.
                func apply(_ change: Change) {
                    switch change {

            """);
        foreach (var member in schema.Members(ContractRoot.Change))
            code.Append($"        case .{Naming.SwiftMember(member.Name)}(let change): apply(change)\n");
        code.Append("        }\n    }\n}\n");

        var roots = new Dictionary<Type, (ContractRoot Root, ContractMember Member)>();
        foreach (var root in Enum.GetValues<ContractRoot>())
            foreach (var member in schema.Members(root)) roots[member.Record.Type] = (root, member);
        code.Append("\n// MARK: - Records\n");
        foreach (var record in schema.Records) {
            var conformances = new List<string>();
            if (roots.TryGetValue(record.Type, out var owner) && owner.Root is ContractRoot.Intent or ContractRoot.Query)
                conformances.Add(owner.Root.ToString());
            if (equatable.Contains(record.Type)) conformances.Add("Equatable");
            conformances.Add("Sendable");
            if (record.Fields.Any(field => field.Name == "Id")) conformances.Add("Identifiable");
            code.Append('\n').Append($"struct {record.Name}: {string.Join(", ", conformances)} {{\n");
            if (owner.Root == ContractRoot.Query && roots.ContainsKey(record.Type))
                code.Append($"    typealias Answer = {TypeName(owner.Member.Answer!)}\n\n");
            foreach (var field in record.Fields)
                code.Append($"    let {Naming.SwiftIdentifier(Naming.SwiftMember(field.Name))}: {TypeName(field.Type)}\n");
            code.Append("}\n");
        }

        if (schema.Enums.Count > 0) code.Append("\n// MARK: - Enums\n");
        foreach (var item in schema.Enums) {
            code.Append('\n');
            if (item.IsFlags) {
                code.Append($"struct {item.Name}: OptionSet, Sendable {{\n    let rawValue: Int\n");
                foreach (var member in item.Members.Where(member => member.Value != 0))
                    code.Append($"    static let {Naming.SwiftIdentifier(Naming.SwiftMember(member.Key))} = {item.Name}(rawValue: {member.Value})\n");
            } else {
                code.Append($"enum {item.Name}: Int, CaseIterable, Sendable {{\n");
                foreach (var member in item.Members)
                    code.Append($"    case {Naming.SwiftIdentifier(Naming.SwiftMember(member.Key))} = {member.Value}\n");
            }
            code.Append("}\n");
        }

        if (schema.Sets.Count > 0) code.Append("\n// MARK: - Fixed sets\n");
        foreach (var set in schema.Sets) EmitSet(code, set);
        return code.ToString();
    }

    /// A fixed set becomes a struct with one `static let` per member, built
    /// from the member's wire tag and the literal values of its data. Two
    /// values are equal when they are the same member.
    private static void EmitSet(StringBuilder code, ContractSet set) {
        var properties = set.Properties.Select(property => (Name: Local(property.Name), property.Type)).ToList();
        code.Append('\n').Append($"/// The members of the core's `{set.Name}`. A member's wire tag is its index in `all`.\n");
        if (set.CoreOnly.Count > 0)
            code.Append($"/// Core-only behavior, not emitted: {string.Join(", ", set.CoreOnly.Select(name => $"`{name}`"))}.\n");
        code.Append($"struct {set.Name}: Hashable, Sendable {{\n");
        foreach (var kinds in set.Properties.Select(property => property.Type).OfType<KindsField>()) {
            code.Append($"    enum {kinds.Type.Name}: Sendable {{\n");
            foreach (string kind in Enum.GetNames(kinds.Type)) code.Append($"        case {Local(kind)}\n");
            code.Append("    }\n\n");
        }
        code.Append("    let tag: Int\n");
        foreach (var property in properties) code.Append($"    let {property.Name}: {TypeName(property.Type)}\n");
        code.Append('\n').Append(Wrapped("    private init(", ")", [
            "tag: Int", .. properties.Select(property => $"{property.Name}: {TypeName(property.Type)}")]));
        code.Append(" {\n        self.tag = tag\n");
        foreach (var property in properties) code.Append($"        self.{property.Name} = {property.Name}\n");
        code.Append("    }\n\n");
        foreach (var member in set.Members)
            code.Append(Wrapped($"    static let {Local(member.Name)} = {set.Name}(", ")", [
                $"tag: {member.Tag}",
                .. properties.Select((property, index) => $"{property.Name}: {Literal(property.Type, member.Values[index])}")])).Append('\n');
        code.Append('\n').Append(Wrapped($"    static let all: [{set.Name}] = [", "]", [.. set.Members.Select(member => Local(member.Name))]))
            .Append('\n');
        code.Append('\n').Append($"    static func named(_ name: String?) -> {set.Name}? {{\n        all.first {{ $0.name == name }}\n    }}\n");
        code.Append('\n').Append($"    static func == (lhs: {set.Name}, rhs: {set.Name}) -> Bool {{\n        lhs.tag == rhs.tag\n    }}\n");
        code.Append('\n').Append("    func hash(into hasher: inout Hasher) {\n        hasher.combine(tag)\n    }\n}\n");
    }

    private static void EmitUnion(StringBuilder code, ContractSchema schema, ContractRoot root, string documentation,
        HashSet<Type> equatable, string conformances) {
        var members = schema.Members(root);
        bool isEquatable = members.All(member => equatable.Contains(member.Record.Type));
        code.Append('\n').Append(documentation).Append('\n');
        code.Append($"enum {root}: {(isEquatable ? "Equatable, " : "")}{conformances} {{\n");
        foreach (var member in members) code.Append($"    case {Naming.SwiftMember(member.Name)}({member.Name})\n");
        code.Append("}\n");
    }

    /// A record is Equatable unless it holds, directly or through its fields,
    /// an intent or a query existential.
    private static HashSet<Type> EquatableRecords(ContractSchema schema) {
        var records = schema.Records.ToDictionary(record => record.Type);
        var excluded = new HashSet<Type>();
        bool changed = true;
        while (changed) {
            changed = false;
            foreach (var record in records.Values.Where(record => !excluded.Contains(record.Type)))
                if (record.Fields.Any(field => !IsEquatable(field.Type, excluded, schema))) changed |= excluded.Add(record.Type);
        }
        return [.. records.Keys.Where(type => !excluded.Contains(type))];
    }

    private static bool IsEquatable(FieldType type, HashSet<Type> excluded, ContractSchema schema) => type switch {
        RecordField record => !excluded.Contains(record.Type),
        RootField { Root: ContractRoot.Intent or ContractRoot.Query } => false,
        RootField root => schema.Members(root.Root).All(member => !excluded.Contains(member.Record.Type)),
        ListField list => IsEquatable(list.Element, excluded, schema),
        OptionalField optional => IsEquatable(optional.Value, excluded, schema),
        _ => true
    };

    #endregion

    #region Actions - Codec

    public static string EmitCodec(ContractSchema schema) {
        ArgumentNullException.ThrowIfNull(schema);
        var code = new StringBuilder(Header);
        code.Append('\n').Append("/// The wire codec's schema identity and the unions Swift decodes.\n");
        code.Append("enum CoreCodec {\n");
        code.Append("    /// SHA-256 of the canonical contract schema. The core refuses any other.\n");
        code.Append("    static let fingerprint: [UInt8] = [\n        ");
        code.Append(string.Join(", ", schema.Fingerprint.Select(value => $"0x{value:x2}"))).Append("\n    ]\n");
        foreach (var root in new[] { ContractRoot.Intent, ContractRoot.Query }) {
            code.Append('\n').Append($"    static func decode{root}(from reader: inout WireReader) throws(WireError) -> any {root} {{\n");
            code.Append("        let tag = try reader.readTag()\n        switch tag {\n");
            foreach (var member in schema.Members(root))
                code.Append($"        case {member.Tag}: return try {member.Name}(from: &reader)\n");
            code.Append($"        default: throw WireError.malformed(\"Unknown {root} tag \\(tag)\")\n        }}\n    }}\n");
        }
        code.Append("}\n");

        foreach (var root in new[] { ContractRoot.Change, ContractRoot.Rejection }) {
            var members = schema.Members(root);
            code.Append('\n').Append($"extension {root} {{\n");
            code.Append("    init(from reader: inout WireReader) throws(WireError) {\n");
            code.Append("        let tag = try reader.readTag()\n        switch tag {\n");
            foreach (var member in members)
                code.Append($"        case {member.Tag}: self = .{Naming.SwiftMember(member.Name)}(try {member.Name}(from: &reader))\n");
            code.Append($"        default: throw WireError.malformed(\"Unknown {root} tag \\(tag)\")\n        }}\n    }}\n\n");
            code.Append("    func encode(into writer: inout WireWriter) {\n        switch self {\n");
            foreach (var member in members) {
                code.Append($"        case .{Naming.SwiftMember(member.Name)}(let value):\n");
                code.Append($"            writer.writeTag({member.Tag})\n            value.encode(into: &writer)\n");
            }
            code.Append("        }\n    }\n}\n");
        }

        var tags = new Dictionary<Type, (ContractRoot Root, ContractMember Member)>();
        foreach (var root in new[] { ContractRoot.Intent, ContractRoot.Query })
            foreach (var member in schema.Members(root)) tags[member.Record.Type] = (root, member);
        foreach (var record in schema.Records) {
            code.Append('\n').Append($"extension {record.Name} {{\n");
            code.Append("    init(from reader: inout WireReader) throws(WireError) {\n");
            var lines = new List<string>();
            foreach (var field in record.Fields) Decode(field.Type, Local(field.Name), lines, "        ");
            foreach (var line in lines) code.Append(line).Append('\n');
            code.Append("        self.init(");
            code.Append(string.Join(", ", record.Fields.Select(field => $"{Naming.SwiftMember(field.Name)}: {Local(field.Name)}")));
            code.Append(")\n    }\n\n");
            code.Append("    func encode(into writer: inout WireWriter) {\n");
            foreach (var field in record.Fields)
                code.Append(Encode(field.Type, Naming.SwiftIdentifier(Naming.SwiftMember(field.Name)), "        ", 0));
            code.Append("    }\n");
            if (tags.TryGetValue(record.Type, out var owner)) {
                code.Append('\n').Append($"    func encode{owner.Root}(into writer: inout WireWriter) {{\n");
                code.Append($"        writer.writeTag({owner.Member.Tag})\n        encode(into: &writer)\n    }}\n");
                if (owner.Root == ContractRoot.Query) {
                    var answer = new List<string>();
                    Decode(owner.Member.Answer!, "answer", answer, "        ");
                    code.Append('\n').Append($"    static func decodeAnswer(from reader: inout WireReader) throws(WireError) -> {TypeName(owner.Member.Answer!)} {{\n");
                    foreach (var line in answer) code.Append(line).Append('\n');
                    code.Append("        return answer\n    }\n");
                }
            }
            code.Append("}\n");
        }

        foreach (var item in schema.Enums) {
            code.Append('\n').Append($"extension {item.Name} {{\n");
            code.Append("    init(from reader: inout WireReader) throws(WireError) {\n");
            code.Append("        let rawValue = try reader.readEnum()\n");
            if (item.IsFlags) {
                int mask = item.Members.Aggregate(0, (bits, member) => bits | member.Value);
                code.Append($"        guard rawValue & ~{mask} == 0 else {{ throw WireError.malformed(\"Unknown {item.Name} \\(rawValue)\") }}\n");
                code.Append("        self.init(rawValue: rawValue)\n");
            } else {
                code.Append($"        guard let value = {item.Name}(rawValue: rawValue) else {{\n");
                code.Append($"            throw WireError.malformed(\"Unknown {item.Name} \\(rawValue)\")\n        }}\n");
                code.Append("        self = value\n");
            }
            code.Append("    }\n\n    func encode(into writer: inout WireWriter) {\n        writer.writeEnum(rawValue)\n    }\n}\n");
        }

        foreach (var set in schema.Sets) {
            code.Append('\n').Append($"extension {set.Name} {{\n");
            code.Append("    init(from reader: inout WireReader) throws(WireError) {\n");
            code.Append("        let tag = try reader.readEnum()\n");
            code.Append($"        guard Self.all.indices.contains(tag) else {{\n            throw WireError.malformed(\"Unknown {set.Name} \\(tag)\")\n        }}\n");
            code.Append("        self = Self.all[tag]\n");
            code.Append("    }\n\n    func encode(into writer: inout WireWriter) {\n        writer.writeEnum(tag)\n    }\n}\n");
        }
        return code.ToString();
    }

    #endregion

    #region Actions - Fields

    private static string Local(string name) => Naming.SwiftIdentifier(Naming.SwiftMember(name));

    /// Appends statements that declare `name` with the decoded value.
    private static void Decode(FieldType type, string name, List<string> lines, string indent) {
        string plain = name.Trim('`');
        switch (type) {
            case PrimitiveField primitive:
                lines.Add($"{indent}let {name} = try reader.read{Method(primitive.Kind)}()");
                break;
            case EnumField or SetField or RecordField:
                lines.Add($"{indent}let {name} = try {TypeName(type)}(from: &reader)");
                break;
            case RootField { Root: ContractRoot.Intent or ContractRoot.Query } root:
                lines.Add($"{indent}let {name} = try CoreCodec.decode{root.Root}(from: &reader)");
                break;
            case RootField root:
                lines.Add($"{indent}let {name} = try {root.Root}(from: &reader)");
                break;
            case ListField list:
                lines.Add($"{indent}let {plain}Count = try reader.readCount()");
                lines.Add($"{indent}var {name}: {TypeName(list)} = []");
                lines.Add($"{indent}{name}.reserveCapacity({plain}Count)");
                lines.Add($"{indent}for _ in 0..<{plain}Count {{");
                Decode(list.Element, $"{plain}Element", lines, indent + "    ");
                lines.Add($"{indent}    {name}.append({plain}Element)");
                lines.Add($"{indent}}}");
                break;
            case OptionalField optional:
                lines.Add($"{indent}let {name}: {TypeName(optional)}");
                lines.Add($"{indent}if try reader.readPresence() {{");
                Decode(optional.Value, $"{plain}Value", lines, indent + "    ");
                lines.Add($"{indent}    {name} = {plain}Value");
                lines.Add($"{indent}}} else {{");
                lines.Add($"{indent}    {name} = nil");
                lines.Add($"{indent}}}");
                break;
            default:
                throw new ContractSchemaException($"Unknown field type {type}.");
        }
    }

    private static string Encode(FieldType type, string value, string indent, int depth) => type switch {
        PrimitiveField primitive => $"{indent}writer.write{Method(primitive.Kind)}({value})\n",
        RootField { Root: ContractRoot.Intent or ContractRoot.Query } root => $"{indent}{value}.encode{root.Root}(into: &writer)\n",
        EnumField or SetField or RecordField or RootField => $"{indent}{value}.encode(into: &writer)\n",
        ListField list => $"{indent}writer.writeCount({value}.count)\n"
            + $"{indent}for element{depth} in {value} {{\n"
            + Encode(list.Element, $"element{depth}", indent + "    ", depth + 1)
            + $"{indent}}}\n",
        OptionalField optional => $"{indent}if let present{depth} = {value} {{\n"
            + $"{indent}    writer.writePresence(true)\n"
            + Encode(optional.Value, $"present{depth}", indent + "    ", depth + 1)
            + $"{indent}}} else {{\n{indent}    writer.writePresence(false)\n{indent}}}\n",
        _ => throw new ContractSchemaException($"Unknown field type {type}.")
    };

    private static string Method(Primitive kind) => kind switch {
        Primitive.Bool => "Bool",
        Primitive.Int => "Int",
        Primitive.Long => "Int64",
        Primitive.Double => "Double",
        Primitive.String => "String",
        Primitive.Guid => "UUID",
        Primitive.Date => "Date",
        Primitive.Duration => "TimeInterval",
        _ => throw new ContractSchemaException($"Unknown primitive {kind}.")
    };

    private static string TypeName(FieldType type) => type switch {
        PrimitiveField primitive => Method(primitive.Kind),
        EnumField item => item.Type.Name,
        SetField set => set.Type.Name,
        LocalizedField => "LocalizedStringResource",
        KindsField kinds => kinds.Type.Name,
        RecordField record => record.Type.Name,
        RootField { Root: ContractRoot.Intent or ContractRoot.Query } root => $"any {root.Root}",
        RootField root => root.Root.ToString(),
        ListField list => $"[{TypeName(list.Element)}]",
        OptionalField { Value: RootField { Root: ContractRoot.Intent or ContractRoot.Query } } optional => $"({TypeName(optional.Value)})?",
        OptionalField optional => $"{TypeName(optional.Value)}?",
        _ => throw new ContractSchemaException($"Unknown field type {type}.")
    };

    #endregion

    #region Actions - Literals

    private const int LineLength = 120;

    /// `open` and `close` around the items on one line when it fits, or one
    /// item per line, indented one level deeper than `open`.
    private static string Wrapped(string open, string close, IReadOnlyList<string> items) {
        string line = $"{open}{string.Join(", ", items)}{close}";
        if (line.Length <= LineLength) return line;
        string indent = new(' ', open.Length - open.TrimStart().Length);
        return $"{open}\n{string.Join(",\n", items.Select(item => $"{indent}    {item}"))}\n{indent}{close}";
    }

    /// A fixed set member's data value as a Swift literal.
    private static string Literal(FieldType type, object? value) => (type, value) switch {
        (OptionalField, null) => "nil",
        (OptionalField optional, _) => Literal(optional.Value, value),
        (PrimitiveField, bool flag) => flag ? "true" : "false",
        (PrimitiveField, int or long) => Convert.ToString(value, CultureInfo.InvariantCulture)!,
        (PrimitiveField, double number) => DoubleLiteral(number),
        (PrimitiveField, TimeSpan duration) => DoubleLiteral(duration.TotalSeconds),
        (PrimitiveField, string text) => StringLiteral(text),
        (SetField, SetMemberReference reference) => $"{reference.Set.Name}.{Local(reference.Member)}",
        (KindsField, Enum kind) => $".{Local(kind.ToString())}",
        (LocalizedField, LocalizedText text) => text.Comment is { } comment
            ? $"LocalizedStringResource({StringLiteral(text.Text)}, comment: {StringLiteral(comment)})"
            : $"LocalizedStringResource({StringLiteral(text.Text)})",
        _ => throw new ContractSchemaException($"Cannot spell {value} as a Swift {TypeName(type)}.")
    };

    private static string DoubleLiteral(double number) => number switch {
        double.NaN => ".nan",
        double.PositiveInfinity => ".infinity",
        double.NegativeInfinity => "-.infinity",
        _ => number.ToString("R", CultureInfo.InvariantCulture)
    };

    private static string StringLiteral(string text) {
        var literal = new StringBuilder("\"");
        foreach (var rune in text.EnumerateRunes())
            literal.Append(rune.Value switch {
                '\\' => "\\\\",
                '"' => "\\\"",
                '\n' => "\\n",
                '\r' => "\\r",
                '\t' => "\\t",
                < 0x20 or 0x7f => $"\\u{{{rune.Value:x}}}",
                _ => rune.ToString()
            });
        return literal.Append('"').ToString();
    }

    #endregion
}
