namespace CrestCore.Application;

internal enum PolicyOperation {
    Unknown,
    AddressIntent,
    AuthenticationFixtureTrust,
    AuthenticationHandling,
    AuthenticationSourceLabel,
    CredentialsCapture,
    CredentialsFill,
    CredentialsMostRecent,
    CredentialsPasswordRecipe,
    CredentialsSaveMatch,
    CredentialsSavePlan,
    CredentialsSaveValidity,
    CredentialsSystemWriteThrough,
    CredentialsSystemWriteThroughOffer,
    DownloadsAutomatic,
    DownloadsProgress,
    DownloadsRisk,
    ExternalConsent,
    ExternalLocalDocument,
    ExternalScheme,
    ExternalUrl,
    GeolocationOrigin,
    HistoryNormalize,
    HistoryRemoveRange,
    HistoryVisit,
    NavigationLink,
    NavigationModifiedLink,
    NotificationsOrigin,
    NotificationsPermissionRequest,
    PasskeysAccessStatus,
    PopupsAutomatic,
    PopupsNotice,
    RecordsExpired,
    ResidencyProcessRecovery,
    ResidencyReleaseLimit,
    ResidencyReleasePlan,
    SearchCustomProvider,
    SearchCustomProviders,
    SearchUrl,
    TabsDismissal,
    TranslationMatches,
    TranslationRule,
    TranslationSet,
}

internal static class PolicyOperationCodes {
    #region Actions - Decoding

    public static PolicyOperation Parse(string? value) => value switch {
        "address.intent" => PolicyOperation.AddressIntent,
        "authentication.fixture_trust" => PolicyOperation.AuthenticationFixtureTrust,
        "authentication.handling" => PolicyOperation.AuthenticationHandling,
        "authentication.source_label" => PolicyOperation.AuthenticationSourceLabel,
        "credentials.capture" => PolicyOperation.CredentialsCapture,
        "credentials.fill" => PolicyOperation.CredentialsFill,
        "credentials.most_recent" => PolicyOperation.CredentialsMostRecent,
        "credentials.password_recipe" => PolicyOperation.CredentialsPasswordRecipe,
        "credentials.save_match" => PolicyOperation.CredentialsSaveMatch,
        "credentials.save_plan" => PolicyOperation.CredentialsSavePlan,
        "credentials.save_validity" => PolicyOperation.CredentialsSaveValidity,
        "credentials.system_write_through" => PolicyOperation.CredentialsSystemWriteThrough,
        "credentials.system_write_through_offer" => PolicyOperation.CredentialsSystemWriteThroughOffer,
        "downloads.automatic" => PolicyOperation.DownloadsAutomatic,
        "downloads.progress" => PolicyOperation.DownloadsProgress,
        "downloads.risk" => PolicyOperation.DownloadsRisk,
        "external.consent" => PolicyOperation.ExternalConsent,
        "external.local_document" => PolicyOperation.ExternalLocalDocument,
        "external.scheme" => PolicyOperation.ExternalScheme,
        "external.url" => PolicyOperation.ExternalUrl,
        "geolocation.origin" => PolicyOperation.GeolocationOrigin,
        "history.normalize" => PolicyOperation.HistoryNormalize,
        "history.remove_range" => PolicyOperation.HistoryRemoveRange,
        "history.visit" => PolicyOperation.HistoryVisit,
        "navigation.link" => PolicyOperation.NavigationLink,
        "navigation.modified_link" => PolicyOperation.NavigationModifiedLink,
        "notifications.origin" => PolicyOperation.NotificationsOrigin,
        "notifications.permission_request" => PolicyOperation.NotificationsPermissionRequest,
        "passkeys.access_status" => PolicyOperation.PasskeysAccessStatus,
        "popups.automatic" => PolicyOperation.PopupsAutomatic,
        "popups.notice" => PolicyOperation.PopupsNotice,
        "records.expired" => PolicyOperation.RecordsExpired,
        "residency.process_recovery" => PolicyOperation.ResidencyProcessRecovery,
        "residency.release_limit" => PolicyOperation.ResidencyReleaseLimit,
        "residency.release_plan" => PolicyOperation.ResidencyReleasePlan,
        "search.custom_provider" => PolicyOperation.SearchCustomProvider,
        "search.custom_providers" => PolicyOperation.SearchCustomProviders,
        "search.url" => PolicyOperation.SearchUrl,
        "tabs.dismissal" => PolicyOperation.TabsDismissal,
        "translation.matches" => PolicyOperation.TranslationMatches,
        "translation.rule" => PolicyOperation.TranslationRule,
        "translation.set" => PolicyOperation.TranslationSet,
        _ => PolicyOperation.Unknown
    };

    #endregion
}
