namespace CrestCore.Application;

internal enum PolicyOperation {
    Unknown,
    AddressIntent,
    AuthenticationFixtureTrust,
    AuthenticationHandling,
    AuthenticationSourceLabel,
    DownloadsAutomatic,
    ExternalLocalDocument,
    ExternalScheme,
    ExternalUrl,
    GeolocationOrigin,
    HistoryNormalize,
    LaunchPlan,
    Limits,
    MediaArbitrate,
    MediaSessionEvent,
    NavigationLink,
    NavigationModifiedLink,
    NotificationsOrigin,
    NotificationsPermissionRequest,
    OnboardingCompletion,
    OnboardingGuide,
    PopupsNotice,
    ResidencyProcessRecovery,
    ResidencyReleaseLimit,
    ResidencyReleasePlan,
    SearchCustomProviders,
    SearchUrl,
    SetupReconcile,
    SetupSpace,
    SetupTab,
    ShortcutsAssign,
    ShortcutsBindings,
    ShortcutsNumberedSelection,
    TabsDismissal,
    TabsSelectionFallback,
    TranslationMatches,
    TranslationRule,
    // Links, Quick Windows, presentation, branding and workspace routing.
    BrandingNormalize,
    LinksRouteCreate,
    LinksRouteMove,
    LinksRouteRemove,
    LinksRouteUpdate,
    LinksSpaceRemoved,
    PagePresentation,
    QuickWindowArchiveLifetime,
    QuickWindowDismissal,
    QuickWindowRetarget,
    WorkspaceCommandRoute,
    WindowRepair,
    WindowSplitLayout,
    WindowTearOff,
}

internal static class PolicyOperationCodes {
    #region Actions - Decoding

    public static PolicyOperation Parse(string? value) => value switch {
        "address.intent" => PolicyOperation.AddressIntent,
        "authentication.fixture_trust" => PolicyOperation.AuthenticationFixtureTrust,
        "authentication.handling" => PolicyOperation.AuthenticationHandling,
        "authentication.source_label" => PolicyOperation.AuthenticationSourceLabel,
        "downloads.automatic" => PolicyOperation.DownloadsAutomatic,
        "external.local_document" => PolicyOperation.ExternalLocalDocument,
        "external.scheme" => PolicyOperation.ExternalScheme,
        "external.url" => PolicyOperation.ExternalUrl,
        "geolocation.origin" => PolicyOperation.GeolocationOrigin,
        "history.normalize" => PolicyOperation.HistoryNormalize,
        "launch.plan" => PolicyOperation.LaunchPlan,
        "limits" => PolicyOperation.Limits,
        "media.arbitrate" => PolicyOperation.MediaArbitrate,
        "media.session_event" => PolicyOperation.MediaSessionEvent,
        "navigation.link" => PolicyOperation.NavigationLink,
        "navigation.modified_link" => PolicyOperation.NavigationModifiedLink,
        "notifications.origin" => PolicyOperation.NotificationsOrigin,
        "notifications.permission_request" => PolicyOperation.NotificationsPermissionRequest,
        "onboarding.completion" => PolicyOperation.OnboardingCompletion,
        "onboarding.guide" => PolicyOperation.OnboardingGuide,
        "popups.notice" => PolicyOperation.PopupsNotice,
        "residency.process_recovery" => PolicyOperation.ResidencyProcessRecovery,
        "residency.release_limit" => PolicyOperation.ResidencyReleaseLimit,
        "residency.release_plan" => PolicyOperation.ResidencyReleasePlan,
        "search.custom_providers" => PolicyOperation.SearchCustomProviders,
        "search.url" => PolicyOperation.SearchUrl,
        "setup.reconcile" => PolicyOperation.SetupReconcile,
        "setup.space" => PolicyOperation.SetupSpace,
        "setup.tab" => PolicyOperation.SetupTab,
        "shortcuts.assign" => PolicyOperation.ShortcutsAssign,
        "shortcuts.bindings" => PolicyOperation.ShortcutsBindings,
        "shortcuts.numbered_selection" => PolicyOperation.ShortcutsNumberedSelection,
        "tabs.dismissal" => PolicyOperation.TabsDismissal,
        "tabs.selection_fallback" => PolicyOperation.TabsSelectionFallback,
        "translation.matches" => PolicyOperation.TranslationMatches,
        "translation.rule" => PolicyOperation.TranslationRule,
        // Links, Quick Windows, presentation, branding and workspace routing.
        "branding.normalize" => PolicyOperation.BrandingNormalize,
        "links.route_create" => PolicyOperation.LinksRouteCreate,
        "links.route_move" => PolicyOperation.LinksRouteMove,
        "links.route_remove" => PolicyOperation.LinksRouteRemove,
        "links.route_update" => PolicyOperation.LinksRouteUpdate,
        "links.space_removed" => PolicyOperation.LinksSpaceRemoved,
        "page.presentation" => PolicyOperation.PagePresentation,
        "quick_window.archive_lifetime" => PolicyOperation.QuickWindowArchiveLifetime,
        "quick_window.dismissal" => PolicyOperation.QuickWindowDismissal,
        "quick_window.retarget" => PolicyOperation.QuickWindowRetarget,
        "workspace.command_route" => PolicyOperation.WorkspaceCommandRoute,
        "window.repair" => PolicyOperation.WindowRepair,
        "window.split_layout" => PolicyOperation.WindowSplitLayout,
        "window.tear_off" => PolicyOperation.WindowTearOff,
        _ => PolicyOperation.Unknown
    };

    #endregion
}
