#!/usr/bin/env python3
"""Generate Crest's emoji picker catalog from Unicode's official test data."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import sys
import textwrap
from urllib.request import Request, urlopen


REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_UNICODE_VERSION = "17.0"
DEFAULT_SOURCE_URL = (
    f"https://www.unicode.org/Public/{DEFAULT_UNICODE_VERSION}.0/emoji/emoji-test.txt"
)
DEFAULT_OUTPUT = (
    REPOSITORY_ROOT
    / "CrestShared"
    / "Features"
    / "Sidebar"
    / "Components"
    / "BrowserTabOrganizationMenu"
    / "Support"
    / "BrowserTabEmojiChoices.swift"
)

GROUP_CATEGORIES = {
    "Smileys & Emotion": "people",
    "People & Body": "people",
    "Animals & Nature": "nature",
    "Food & Drink": "food",
    "Activities": "activity",
    "Travel & Places": "travel",
    "Objects": "objects",
    "Symbols": "symbols",
    "Flags": "flags",
}

ENTRY_PATTERN = re.compile(
    r"^\s*([0-9A-F ]+)\s*;\s*([a-z-]+)\s*"
    r"#\s+\S+\s+E([0-9.]+)\s+(.+)$"
)
VERSION_PATTERN = re.compile(r"^# Version:\s*([0-9.]+)\s*$")


def sentence_case(name: str) -> str:
    return name[:1].upper() + name[1:]


def parse_emoji_test(source: str) -> tuple[str, list[dict[str, object]]]:
    unicode_version = ""
    group = ""
    subgroup = ""
    entries: list[dict[str, object]] = []

    for line_number, line in enumerate(source.splitlines(), start=1):
        if version_match := VERSION_PATTERN.match(line):
            unicode_version = version_match.group(1)
            continue
        if line.startswith("# group: "):
            group = line.removeprefix("# group: ").strip()
            continue
        if line.startswith("# subgroup: "):
            subgroup = line.removeprefix("# subgroup: ").strip()
            continue

        match = ENTRY_PATTERN.match(line)
        if match is None:
            continue
        code_points, qualification, emoji_version, name = match.groups()
        if qualification != "fully-qualified":
            continue
        try:
            category = GROUP_CATEGORIES[group]
        except KeyError as error:
            raise ValueError(
                f"Unknown Unicode emoji group {group!r} on line {line_number}."
            ) from error

        emoji = "".join(chr(int(code_point, 16)) for code_point in code_points.split())
        entries.append(
            {
                "emoji": emoji,
                "name": sentence_case(name),
                "category": category,
                "subgroup": subgroup,
                "version": float(emoji_version),
            }
        )

    if not unicode_version:
        raise ValueError("The Unicode source did not declare an emoji version.")
    if not entries:
        raise ValueError("The Unicode source did not contain fully-qualified emoji.")
    return unicode_version, entries


def build_catalog(source: str, source_url: str) -> dict[str, object]:
    unicode_version, entries = parse_emoji_test(source)
    return {
        "metadata": {
            "unicodeVersion": unicode_version,
            "sourceURL": source_url,
            "sourceSHA256": hashlib.sha256(source.encode("utf-8")).hexdigest(),
            "fullyQualifiedCount": len(entries),
        },
        "entries": entries,
    }


def render_swift(catalog: dict[str, object]) -> str:
    payload = json.dumps(
        catalog,
        ensure_ascii=False,
        indent=2,
        separators=(",", ": "),
    )
    indented_payload = textwrap.indent(payload, "        ")
    return f'''// Generated by Scripts/generate-emoji-catalog.py from Unicode's
// emoji-test.txt. Do not hand-edit this catalog; regenerate it instead.

extension BrowserTabEmojiChoices {{
    static let generatedCatalogJSONString = #"""
{indented_payload}
        """#
}}
'''


def download_source(source_url: str) -> str:
    request = Request(source_url, headers={"User-Agent": "Crest emoji catalog generator"})
    with urlopen(request, timeout=30) as response:
        return response.read().decode("utf-8")


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        type=Path,
        help="Read emoji-test.txt from this path instead of Unicode's website.",
    )
    parser.add_argument(
        "--source-url",
        help="Override the official URL derived from --unicode-version.",
    )
    parser.add_argument("--unicode-version", default=DEFAULT_UNICODE_VERSION)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the generated source differs instead of rewriting it.",
    )
    return parser.parse_args()


def main() -> int:
    arguments = parse_arguments()
    source_url = arguments.source_url or (
        f"https://www.unicode.org/Public/{arguments.unicode_version}.0/"
        "emoji/emoji-test.txt"
    )
    source = (
        arguments.source.read_text(encoding="utf-8")
        if arguments.source is not None
        else download_source(source_url)
    )
    catalog = build_catalog(source, source_url)
    actual_version = catalog["metadata"]["unicodeVersion"]
    if actual_version != arguments.unicode_version:
        print(
            f"error: expected Unicode Emoji {arguments.unicode_version}, "
            f"found {actual_version}",
            file=sys.stderr,
        )
        return 1

    generated = render_swift(catalog)
    if arguments.check:
        current = (
            arguments.output.read_text(encoding="utf-8")
            if arguments.output.is_file()
            else ""
        )
        if current != generated:
            print(
                f"error: {arguments.output} is not the generated Unicode "
                f"Emoji {arguments.unicode_version} catalog",
                file=sys.stderr,
            )
            return 1
        return 0

    arguments.output.write_text(generated, encoding="utf-8")
    print(
        f"Generated {catalog['metadata']['fullyQualifiedCount']} fully-qualified "
        f"emoji from Unicode Emoji {actual_version}."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
