import Foundation

/// One command or read of the family's core session. Raw values are the core's
/// spellings in `SessionOperation.cs`. App-wide `preferences.*` commands have
/// their own request model, `BrowserAppPreferenceCommand`.
enum BrowserSessionOperation: String, Codable, Sendable {
    case archiveRestore = "archive.restore"
    case folderCollapse = "folder.collapse"
    case folderColor = "folder.color"
    case folderCreate = "folder.create"
    case folderDelete = "folder.delete"
    case folderMove = "folder.move"
    case folderRename = "folder.rename"
    case folderSymbol = "folder.symbol"
    case historyClear = "history.clear"
    case historyRemoveRange = "history.remove_range"
    case historyRemoveURL = "history.remove_url"
    case historyVisit = "history.visit"
    case launchPlan = "launch.plan"
    case recordsCleanup = "records.cleanup"
    case recordsSweep = "records.sweep"
    case spaceAccess = "space.access"
    case spaceBranding = "space.branding"
    case spaceBrowsingPreferences = "space.browsing_preferences"
    case spaceCreate = "space.create"
    case spaceCredentialPreferences = "space.credential_preferences"
    case spaceDefault = "space.default"
    case spaceDeletionBegin = "space.deletion.begin"
    case spaceIdentity = "space.identity"
    case spaceRemove = "space.remove"
    case spaceReorder = "space.reorder"
    case spaceResetPrivate = "space.reset_private"
    case spaceSavedExpansion = "space.saved_expansion"
    case spaceSearchProviderRemove = "space.search_provider.remove"
    case spaceSearchProviderUpsert = "space.search_provider.upsert"
    case splitDissolve = "split.dissolve"
    case splitIcon = "split.icon"
    case splitJoin = "split.join"
    case splitJoinInPlace = "split.join_in_place"
    case splitLeave = "split.leave"
    case splitMove = "split.move"
    case splitOpenLink = "split.open_link"
    case splitReorder = "split.reorder"
    case splitTint = "split.tint"
    case splitTitle = "split.title"
    case tabTouch = "tab.touch"
    case tabArchiveTransient = "tab.archive_transient"
    case tabCleanup = "tab.cleanup"
    case tabClearCurrent = "tab.clear_current"
    case tabClose = "tab.close"
    case tabCloseDurable = "tab.close_durable"
    case tabCopy = "tab.copy"
    case tabDelete = "tab.delete"
    case tabFaviconCache = "tab.favicon.cache"
    case tabIcon = "tab.icon"
    case tabMove = "tab.move"
    case tabObserve = "tab.observe"
    case tabOpen = "tab.open"
    case tabPromoteTransient = "tab.promote_transient"
    case tabRename = "tab.rename"
    case tabResidency = "tab.residency"
    case tabRestoreArchive = "tab.restore_archive"
    case tabSavedLocation = "tab.saved_location"
    case tabTransfer = "tab.transfer"
    case tabsBatch = "tabs.batch"
    case tabsFile = "tabs.file"
    case transientArchive = "transient.archive"
    case transientPromote = "transient.promote"
    case workspaceImport = "workspace.import"
}
