import Foundation

/// One stateless core policy call. Raw values are the core's spellings in
/// `PolicyOperation.cs`.
enum BrowserPolicyOperation: String, Codable, Sendable {
    case addressIntent = "address.intent"
    case authenticationFixtureTrust = "authentication.fixture_trust"
    case authenticationHandling = "authentication.handling"
    case authenticationSourceLabel = "authentication.source_label"
    case downloadsAutomatic = "downloads.automatic"
    case externalLocalDocument = "external.local_document"
    case externalScheme = "external.scheme"
    case externalURL = "external.url"
    case geolocationOrigin = "geolocation.origin"
    case historyNormalize = "history.normalize"
    case launchPlan = "launch.plan"
    case limits
    case mediaArbitrate = "media.arbitrate"
    case mediaSessionEvent = "media.session_event"
    case navigationLink = "navigation.link"
    case navigationModifiedLink = "navigation.modified_link"
    case notificationsOrigin = "notifications.origin"
    case notificationsPermissionRequest = "notifications.permission_request"
    case onboardingCompletion = "onboarding.completion"
    case onboardingGuide = "onboarding.guide"
    case popupsNotice = "popups.notice"
    case residencyProcessRecovery = "residency.process_recovery"
    case residencyReleaseLimit = "residency.release_limit"
    case residencyReleasePlan = "residency.release_plan"
    case searchCustomProviders = "search.custom_providers"
    case searchURL = "search.url"
    case setupReconcile = "setup.reconcile"
    case setupSpace = "setup.space"
    case setupTab = "setup.tab"
    case translationMatches = "translation.matches"
    case translationRule = "translation.rule"
    case brandingNormalize = "branding.normalize"
    case linksRouteCreate = "links.route_create"
    case linksRouteMove = "links.route_move"
    case linksRouteRemove = "links.route_remove"
    case linksRouteUpdate = "links.route_update"
    case linksSpaceRemoved = "links.space_removed"
    case pagePresentation = "page.presentation"
    case quickWindowDismissal = "quick_window.dismissal"
    case quickWindowRetarget = "quick_window.retarget"
}
