// <auto-generated/>
// Generated by CrestCore/tools/CrestCore.Generator from the C# contract records. Do not edit.
//
// The engine contract of crest_engine.h in C++: the commands the core
// issues to an engine binding, the events a binding reports, and the
// registration it hands the core, with their positional wire codec.
// Lengths, counts, tags and enums are LEB128 varints; numbers are
// fixed-width little-endian; a GUID is 16 bytes in RFC 4122 order; a
// string is its UTF-8 length and bytes; an optional is a presence byte;
// a union is its root's tag, the member's index, followed by its fields.
#ifndef CREST_ENGINE_CONTRACT_H_
#define CREST_ENGINE_CONTRACT_H_

#include <array>
#include <bit>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <limits>
#include <optional>
#include <string>
#include <type_traits>
#include <utility>
#include <variant>
#include <vector>

namespace crest::engine {

// SHA-256 of the engine contract alone. A binding registers with it, so the
// core refuses an engine built against any other contract.
inline constexpr std::array<uint8_t, 32> kFingerprint = {
    0xca, 0xe7, 0x4a, 0xfc, 0xf6, 0x21, 0xbb, 0xec, 0xb1, 0xa0, 0x07, 0x81, 0xd1, 0xa4, 0x53, 0x62, 0xda, 0x4a, 0x38, 0x79, 0x8b, 0xf4, 0xc8, 0xca, 0x97, 0xd3, 0x4c, 0xbd, 0xa7, 0xb8, 0x33, 0x25};

// A GUID in RFC 4122 byte order, as the wire carries it.
using Guid = std::array<uint8_t, 16>;
// A byte string.
using Bytes = std::vector<uint8_t>;

// Seconds since 1 January 2001, as the wire carries a date.
struct Date {
  double seconds_since_2001 = 0;
  friend bool operator==(const Date&, const Date&) = default;
};

// Seconds, as the wire carries a duration.
struct Duration {
  double seconds = 0;
  friend bool operator==(const Duration&, const Duration&) = default;
};

// Writes the positional wire format.
class WireWriter {
 public:
  const std::vector<uint8_t>& bytes() const { return bytes_; }
  std::vector<uint8_t> Take() { return std::move(bytes_); }

  void WriteVarint(uint64_t value) {
    do {
      uint8_t next = static_cast<uint8_t>(value & 0x7f);
      value >>= 7;
      bytes_.push_back(value == 0 ? next : static_cast<uint8_t>(next | 0x80));
    } while (value != 0);
  }
  void WriteFixed(uint64_t bits, size_t width) {
    for (size_t index = 0; index < width; ++index) {
      bytes_.push_back(static_cast<uint8_t>(bits >> (8 * index)));
    }
  }
  void WriteRaw(const uint8_t* data, size_t length) { bytes_.insert(bytes_.end(), data, data + length); }

 private:
  std::vector<uint8_t> bytes_;
};

// Reads the positional wire format. A malformed message fails the reader,
// and every later read answers a default value, so a caller checks `ok()`
// once, after reading the whole message.
class WireReader {
 public:
  WireReader(const uint8_t* data, size_t length) : data_(data), length_(data ? length : 0) {}

  bool ok() const { return !failed_; }
  bool AtEnd() const { return position_ == length_; }
  size_t remaining() const { return length_ - position_; }
  void Fail() { failed_ = true; }

  uint64_t ReadVarint() {
    uint64_t value = 0;
    for (int shift = 0; shift < 64; shift += 7) {
      const uint8_t* next = Take(1);
      if (!next) return 0;
      const uint64_t bits = *next & 0x7f;
      if (shift == 63 && bits > 1) return Failed();
      value |= bits << shift;
      if ((*next & 0x80) == 0) {
        if (*next == 0 && shift > 0) return Failed();
        return value;
      }
    }
    return Failed();
  }
  // A union's tag, a varint of at most 31 bits.
  uint32_t ReadTag() { return static_cast<uint32_t>(ReadBounded(std::numeric_limits<int32_t>::max())); }
  // A list's count; every element takes at least one byte.
  size_t ReadCount() { return static_cast<size_t>(ReadBounded(remaining())); }
  // A plain enum's value, which must be below `count`.
  uint32_t ReadEnum(uint32_t count) { return static_cast<uint32_t>(ReadBounded(count - 1)); }
  // A flags enum's value, which may set only bits in `mask`.
  uint32_t ReadFlags(uint32_t mask) {
    const uint64_t value = ReadBounded(std::numeric_limits<int32_t>::max());
    if ((value & ~static_cast<uint64_t>(mask)) != 0) return static_cast<uint32_t>(Failed());
    return static_cast<uint32_t>(value);
  }
  bool ReadFlag() {
    const uint8_t* next = Take(1);
    if (!next) return false;
    if (*next > 1) return Failed() != 0;
    return *next == 1;
  }
  uint64_t ReadFixed(size_t width) {
    const uint8_t* next = Take(width);
    uint64_t bits = 0;
    for (size_t index = 0; next && index < width; ++index) {
      bits |= static_cast<uint64_t>(next[index]) << (8 * index);
    }
    return bits;
  }
  const uint8_t* Take(size_t length) {
    if (failed_ || length > remaining()) {
      failed_ = true;
      return nullptr;
    }
    const uint8_t* start = data_ + position_;
    position_ += length;
    return start;
  }

 private:
  uint64_t ReadBounded(uint64_t maximum) {
    const uint64_t value = ReadVarint();
    return value <= maximum ? value : Failed();
  }
  uint64_t Failed() {
    failed_ = true;
    return 0;
  }

  const uint8_t* data_;
  size_t length_;
  size_t position_ = 0;
  bool failed_ = false;
};

// Whether `text` is well-formed UTF-8: no overlong forms, surrogates or
// code points past U+10FFFF, as the core's strict decoder requires.
inline bool IsUtf8(const uint8_t* text, size_t length) {
  size_t index = 0;
  while (index < length) {
    const uint8_t lead = text[index];
    size_t extra = 0;
    uint32_t point = 0;
    if (lead < 0x80) {
      ++index;
      continue;
    } else if (lead >= 0xc2 && lead <= 0xdf) {
      extra = 1;
      point = lead & 0x1f;
    } else if (lead >= 0xe0 && lead <= 0xef) {
      extra = 2;
      point = lead & 0x0f;
    } else if (lead >= 0xf0 && lead <= 0xf4) {
      extra = 3;
      point = lead & 0x07;
    } else {
      return false;
    }
    if (extra > length - index - 1) return false;
    for (size_t next = 1; next <= extra; ++next) {
      const uint8_t continuation = text[index + next];
      if ((continuation & 0xc0) != 0x80) return false;
      point = (point << 6) | (continuation & 0x3f);
    }
    if ((extra == 2 && (point < 0x800 || (point >= 0xd800 && point <= 0xdfff))) ||
        (extra == 3 && (point < 0x10000 || point > 0x10ffff))) {
      return false;
    }
    index += extra + 1;
  }
  return true;
}

inline void Write(WireWriter& writer, bool value) { writer.WriteFixed(value ? 1 : 0, 1); }
inline void Write(WireWriter& writer, int32_t value) { writer.WriteFixed(static_cast<uint32_t>(value), 4); }
inline void Write(WireWriter& writer, int64_t value) { writer.WriteFixed(static_cast<uint64_t>(value), 8); }
inline void Write(WireWriter& writer, uint64_t value) { writer.WriteFixed(value, 8); }
inline void Write(WireWriter& writer, double value) { writer.WriteFixed(std::bit_cast<uint64_t>(value), 8); }
inline void Write(WireWriter& writer, Date value) { Write(writer, value.seconds_since_2001); }
inline void Write(WireWriter& writer, Duration value) { Write(writer, value.seconds); }
inline void Write(WireWriter& writer, const std::string& value) {
  writer.WriteVarint(value.size());
  writer.WriteRaw(reinterpret_cast<const uint8_t*>(value.data()), value.size());
}
inline void Write(WireWriter& writer, const Bytes& value) {
  writer.WriteVarint(value.size());
  writer.WriteRaw(value.data(), value.size());
}
inline void Write(WireWriter& writer, const Guid& value) { writer.WriteRaw(value.data(), value.size()); }
template <typename T>
void Write(WireWriter& writer, const std::optional<T>& value) {
  writer.WriteFixed(value.has_value() ? 1 : 0, 1);
  if (value) Write(writer, *value);
}
template <typename T>
void Write(WireWriter& writer, const std::vector<T>& value) {
  writer.WriteVarint(value.size());
  for (const T& item : value) Write(writer, item);
}

inline bool Read(WireReader& reader, bool& value) {
  value = reader.ReadFlag();
  return reader.ok();
}
inline bool Read(WireReader& reader, int32_t& value) {
  value = static_cast<int32_t>(static_cast<uint32_t>(reader.ReadFixed(4)));
  return reader.ok();
}
inline bool Read(WireReader& reader, int64_t& value) {
  value = static_cast<int64_t>(reader.ReadFixed(8));
  return reader.ok();
}
inline bool Read(WireReader& reader, uint64_t& value) {
  value = reader.ReadFixed(8);
  return reader.ok();
}
inline bool Read(WireReader& reader, double& value) {
  value = std::bit_cast<double>(reader.ReadFixed(8));
  return reader.ok();
}
inline bool Read(WireReader& reader, Date& value) { return Read(reader, value.seconds_since_2001); }
inline bool Read(WireReader& reader, Duration& value) { return Read(reader, value.seconds); }
inline bool Read(WireReader& reader, std::string& value) {
  const size_t length = reader.ReadCount();
  const uint8_t* text = reader.Take(length);
  if (!text || !IsUtf8(text, length)) {
    reader.Fail();
    return false;
  }
  value.assign(reinterpret_cast<const char*>(text), length);
  return true;
}
inline bool Read(WireReader& reader, Bytes& value) {
  const size_t length = reader.ReadCount();
  const uint8_t* data = reader.Take(length);
  if (!data) return false;
  value.assign(data, data + length);
  return true;
}
inline bool Read(WireReader& reader, Guid& value) {
  const uint8_t* data = reader.Take(value.size());
  if (!data) return false;
  std::memcpy(value.data(), data, value.size());
  return true;
}
template <typename T>
bool Read(WireReader& reader, std::optional<T>& value) {
  if (!reader.ReadFlag()) {
    value.reset();
    return reader.ok();
  }
  T present{};
  if (!Read(reader, present)) return false;
  value = std::move(present);
  return true;
}
template <typename T>
bool Read(WireReader& reader, std::vector<T>& value) {
  const size_t count = reader.ReadCount();
  value.clear();
  for (size_t index = 0; index < count && reader.ok(); ++index) {
    T item{};
    if (!Read(reader, item)) return false;
    value.push_back(std::move(item));
  }
  return reader.ok();
}

enum class PageMediaActivity : uint32_t {
  kNone = 0,
  kPlaying = 1,
  kCapturing = 2,
  kPictureInPicture = 4,
};
inline constexpr uint32_t kPageMediaActivityMask = 7;
constexpr PageMediaActivity operator|(PageMediaActivity lhs, PageMediaActivity rhs) {
  return static_cast<PageMediaActivity>(static_cast<uint32_t>(lhs) | static_cast<uint32_t>(rhs));
}
constexpr PageMediaActivity& operator|=(PageMediaActivity& lhs, PageMediaActivity rhs) { return lhs = lhs | rhs; }
constexpr bool Has(PageMediaActivity value, PageMediaActivity flag) {
  return (static_cast<uint32_t>(value) & static_cast<uint32_t>(flag)) != 0;
}
inline void Write(WireWriter& writer, PageMediaActivity value) { writer.WriteVarint(static_cast<uint32_t>(value)); }
inline bool Read(WireReader& reader, PageMediaActivity& value) {
  value = static_cast<PageMediaActivity>(reader.ReadFlags(kPageMediaActivityMask));
  return reader.ok();
}

enum class EngineCapability : uint32_t {
  kPages = 0,
  kNavigation = 1,
  kFind = 2,
  kZoom = 3,
  kInteractionState = 4,
  kPageResidency = 5,
  kPopups = 6,
  kWorkspaceProfiles = 7,
  kWorkspaceTransfer = 8,
  kProfileDeletion = 9,
  kContentBlocking = 10,
  kDownloads = 11,
  kPermissions = 12,
  kReader = 13,
  kTranslation = 14,
  kSelectionTranslation = 15,
  kLocalFiles = 16,
  kExtensions = 17,
  kViewportCapture = 18,
  kFullPageCapture = 19,
  kPdf = 20,
  kWebArchive = 21,
  kPrint = 22,
  kInspector = 23,
  kFeatureFlags = 24,
  kBeforeUnload = 25,
  kInternalPages = 26,
};
inline void Write(WireWriter& writer, EngineCapability value) { writer.WriteVarint(static_cast<uint32_t>(value)); }
inline bool Read(WireReader& reader, EngineCapability& value) {
  value = static_cast<EngineCapability>(reader.ReadEnum(27));
  return reader.ok();
}

enum class EngineKind : uint32_t {
  kChromium = 0,
  kWebKit = 1,
};
inline void Write(WireWriter& writer, EngineKind value) { writer.WriteVarint(static_cast<uint32_t>(value)); }
inline bool Read(WireReader& reader, EngineKind& value) {
  value = static_cast<EngineKind>(reader.ReadEnum(2));
  return reader.ok();
}

enum class NavigationError : uint32_t {
  kOffline = 0,
  kTimedOut = 1,
  kCannotFindServer = 2,
  kCannotConnect = 3,
  kConnectionLost = 4,
  kSecureConnectionFailed = 5,
  kTooManyRedirects = 6,
  kUnsupportedAddress = 7,
  kBlocked = 8,
  kUnavailable = 9,
  kWebContentProcessStopped = 10,
  kUnknown = 11,
};
inline void Write(WireWriter& writer, NavigationError value) { writer.WriteVarint(static_cast<uint32_t>(value)); }
inline bool Read(WireReader& reader, NavigationError& value) {
  value = static_cast<NavigationError>(reader.ReadEnum(12));
  return reader.ok();
}

enum class PageSecurity : uint32_t {
  kNone = 0,
  kInsecure = 1,
  kSecure = 2,
  kMixedContent = 3,
  kCertificateError = 4,
  kDangerous = 5,
};
inline void Write(WireWriter& writer, PageSecurity value) { writer.WriteVarint(static_cast<uint32_t>(value)); }
inline bool Read(WireReader& reader, PageSecurity& value) {
  value = static_cast<PageSecurity>(reader.ReadEnum(6));
  return reader.ok();
}

struct ClosePage {
  Guid page_id = {};
  bool keeps_state = false;

  friend bool operator==(const ClosePage&, const ClosePage&) = default;
};
inline void Write(WireWriter& writer, const ClosePage& value) {
  Write(writer, value.page_id);
  Write(writer, value.keeps_state);
}
inline bool Read(WireReader& reader, ClosePage& value) {
  return Read(reader, value.page_id)
      && Read(reader, value.keeps_state);
}

struct CreatePage {
  Guid page_id = {};
  Guid profile_id = {};
  bool is_private = false;
  Guid window_id = {};

  friend bool operator==(const CreatePage&, const CreatePage&) = default;
};
inline void Write(WireWriter& writer, const CreatePage& value) {
  Write(writer, value.page_id);
  Write(writer, value.profile_id);
  Write(writer, value.is_private);
  Write(writer, value.window_id);
}
inline bool Read(WireReader& reader, CreatePage& value) {
  return Read(reader, value.page_id)
      && Read(reader, value.profile_id)
      && Read(reader, value.is_private)
      && Read(reader, value.window_id);
}

struct EngineRegistration {
  EngineKind kind = {};
  std::vector<EngineCapability> capabilities;
  bool is_default = false;

  friend bool operator==(const EngineRegistration&, const EngineRegistration&) = default;
};
inline void Write(WireWriter& writer, const EngineRegistration& value) {
  Write(writer, value.kind);
  Write(writer, value.capabilities);
  Write(writer, value.is_default);
}
inline bool Read(WireReader& reader, EngineRegistration& value) {
  return Read(reader, value.kind)
      && Read(reader, value.capabilities)
      && Read(reader, value.is_default);
}

struct LoadPage {
  Guid page_id = {};
  std::string url;

  friend bool operator==(const LoadPage&, const LoadPage&) = default;
};
inline void Write(WireWriter& writer, const LoadPage& value) {
  Write(writer, value.page_id);
  Write(writer, value.url);
}
inline bool Read(WireReader& reader, LoadPage& value) {
  return Read(reader, value.page_id)
      && Read(reader, value.url);
}

struct NavigationCommitted {
  Guid page_id = {};
  std::string url;
  bool same_document = false;

  friend bool operator==(const NavigationCommitted&, const NavigationCommitted&) = default;
};
inline void Write(WireWriter& writer, const NavigationCommitted& value) {
  Write(writer, value.page_id);
  Write(writer, value.url);
  Write(writer, value.same_document);
}
inline bool Read(WireReader& reader, NavigationCommitted& value) {
  return Read(reader, value.page_id)
      && Read(reader, value.url)
      && Read(reader, value.same_document);
}

struct PageFailure {
  NavigationError error = {};
  std::optional<std::string> url;
  bool replaced_document = false;
  std::string domain;
  int64_t code = 0;

  friend bool operator==(const PageFailure&, const PageFailure&) = default;
};
inline void Write(WireWriter& writer, const PageFailure& value) {
  Write(writer, value.error);
  Write(writer, value.url);
  Write(writer, value.replaced_document);
  Write(writer, value.domain);
  Write(writer, value.code);
}
inline bool Read(WireReader& reader, PageFailure& value) {
  return Read(reader, value.error)
      && Read(reader, value.url)
      && Read(reader, value.replaced_document)
      && Read(reader, value.domain)
      && Read(reader, value.code);
}

struct NavigationFailed {
  Guid page_id = {};
  PageFailure failure;

  friend bool operator==(const NavigationFailed&, const NavigationFailed&) = default;
};
inline void Write(WireWriter& writer, const NavigationFailed& value) {
  Write(writer, value.page_id);
  Write(writer, value.failure);
}
inline bool Read(WireReader& reader, NavigationFailed& value) {
  return Read(reader, value.page_id)
      && Read(reader, value.failure);
}

struct NavigationFinished {
  Guid page_id = {};
  std::string url;
  std::string title;

  friend bool operator==(const NavigationFinished&, const NavigationFinished&) = default;
};
inline void Write(WireWriter& writer, const NavigationFinished& value) {
  Write(writer, value.page_id);
  Write(writer, value.url);
  Write(writer, value.title);
}
inline bool Read(WireReader& reader, NavigationFinished& value) {
  return Read(reader, value.page_id)
      && Read(reader, value.url)
      && Read(reader, value.title);
}

struct NavigationStarted {
  Guid page_id = {};
  std::string url;
  bool same_document = false;

  friend bool operator==(const NavigationStarted&, const NavigationStarted&) = default;
};
inline void Write(WireWriter& writer, const NavigationStarted& value) {
  Write(writer, value.page_id);
  Write(writer, value.url);
  Write(writer, value.same_document);
}
inline bool Read(WireReader& reader, NavigationStarted& value) {
  return Read(reader, value.page_id)
      && Read(reader, value.url)
      && Read(reader, value.same_document);
}

struct PageClosed {
  Guid page_id = {};

  friend bool operator==(const PageClosed&, const PageClosed&) = default;
};
inline void Write(WireWriter& writer, const PageClosed& value) {
  Write(writer, value.page_id);
}
inline bool Read(WireReader& reader, PageClosed& value) {
  return Read(reader, value.page_id);
}

struct PageCreated {
  Guid page_id = {};

  friend bool operator==(const PageCreated&, const PageCreated&) = default;
};
inline void Write(WireWriter& writer, const PageCreated& value) {
  Write(writer, value.page_id);
}
inline bool Read(WireReader& reader, PageCreated& value) {
  return Read(reader, value.page_id);
}

struct PageCreationFailed {
  Guid page_id = {};

  friend bool operator==(const PageCreationFailed&, const PageCreationFailed&) = default;
};
inline void Write(WireWriter& writer, const PageCreationFailed& value) {
  Write(writer, value.page_id);
}
inline bool Read(WireReader& reader, PageCreationFailed& value) {
  return Read(reader, value.page_id);
}

struct TabIconAccent {
  double red = 0;
  double green = 0;
  double blue = 0;

  friend bool operator==(const TabIconAccent&, const TabIconAccent&) = default;
};
inline void Write(WireWriter& writer, const TabIconAccent& value) {
  Write(writer, value.red);
  Write(writer, value.green);
  Write(writer, value.blue);
}
inline bool Read(WireReader& reader, TabIconAccent& value) {
  return Read(reader, value.red)
      && Read(reader, value.green)
      && Read(reader, value.blue);
}

struct PageIconChanged {
  Guid page_id = {};
  std::string url;
  std::optional<TabIconAccent> accent;

  friend bool operator==(const PageIconChanged&, const PageIconChanged&) = default;
};
inline void Write(WireWriter& writer, const PageIconChanged& value) {
  Write(writer, value.page_id);
  Write(writer, value.url);
  Write(writer, value.accent);
}
inline bool Read(WireReader& reader, PageIconChanged& value) {
  return Read(reader, value.page_id)
      && Read(reader, value.url)
      && Read(reader, value.accent);
}

struct PageSnapshot {
  std::optional<std::string> url;
  std::optional<std::string> pending_url;
  std::string title;
  bool is_loading = false;
  bool can_go_back = false;
  bool can_go_forward = false;
  PageSecurity security = {};
  PageMediaActivity media = {};

  friend bool operator==(const PageSnapshot&, const PageSnapshot&) = default;
};
inline void Write(WireWriter& writer, const PageSnapshot& value) {
  Write(writer, value.url);
  Write(writer, value.pending_url);
  Write(writer, value.title);
  Write(writer, value.is_loading);
  Write(writer, value.can_go_back);
  Write(writer, value.can_go_forward);
  Write(writer, value.security);
  Write(writer, value.media);
}
inline bool Read(WireReader& reader, PageSnapshot& value) {
  return Read(reader, value.url)
      && Read(reader, value.pending_url)
      && Read(reader, value.title)
      && Read(reader, value.is_loading)
      && Read(reader, value.can_go_back)
      && Read(reader, value.can_go_forward)
      && Read(reader, value.security)
      && Read(reader, value.media);
}

struct PageStateChanged {
  Guid page_id = {};
  PageSnapshot snapshot;

  friend bool operator==(const PageStateChanged&, const PageStateChanged&) = default;
};
inline void Write(WireWriter& writer, const PageStateChanged& value) {
  Write(writer, value.page_id);
  Write(writer, value.snapshot);
}
inline bool Read(WireReader& reader, PageStateChanged& value) {
  return Read(reader, value.page_id)
      && Read(reader, value.snapshot);
}

using EngineCommand = std::variant<ClosePage, CreatePage, LoadPage>;
inline void Write(WireWriter& writer, const EngineCommand& value) {
  writer.WriteVarint(value.index());
  std::visit([&writer](const auto& member) { Write(writer, member); }, value);
}
inline bool Read(WireReader& reader, EngineCommand& value) {
  switch (reader.ReadTag()) {
    case 0: {
      ClosePage member;
      if (!Read(reader, member)) return false;
      value = std::move(member);
      return true;
    }
    case 1: {
      CreatePage member;
      if (!Read(reader, member)) return false;
      value = std::move(member);
      return true;
    }
    case 2: {
      LoadPage member;
      if (!Read(reader, member)) return false;
      value = std::move(member);
      return true;
    }
    default:
      reader.Fail();
      return false;
  }
}

using EngineEvent = std::variant<NavigationCommitted, NavigationFailed, NavigationFinished, NavigationStarted, PageClosed, PageCreated, PageCreationFailed, PageIconChanged, PageStateChanged>;
inline void Write(WireWriter& writer, const EngineEvent& value) {
  writer.WriteVarint(value.index());
  std::visit([&writer](const auto& member) { Write(writer, member); }, value);
}
inline bool Read(WireReader& reader, EngineEvent& value) {
  switch (reader.ReadTag()) {
    case 0: {
      NavigationCommitted member;
      if (!Read(reader, member)) return false;
      value = std::move(member);
      return true;
    }
    case 1: {
      NavigationFailed member;
      if (!Read(reader, member)) return false;
      value = std::move(member);
      return true;
    }
    case 2: {
      NavigationFinished member;
      if (!Read(reader, member)) return false;
      value = std::move(member);
      return true;
    }
    case 3: {
      NavigationStarted member;
      if (!Read(reader, member)) return false;
      value = std::move(member);
      return true;
    }
    case 4: {
      PageClosed member;
      if (!Read(reader, member)) return false;
      value = std::move(member);
      return true;
    }
    case 5: {
      PageCreated member;
      if (!Read(reader, member)) return false;
      value = std::move(member);
      return true;
    }
    case 6: {
      PageCreationFailed member;
      if (!Read(reader, member)) return false;
      value = std::move(member);
      return true;
    }
    case 7: {
      PageIconChanged member;
      if (!Read(reader, member)) return false;
      value = std::move(member);
      return true;
    }
    case 8: {
      PageStateChanged member;
      if (!Read(reader, member)) return false;
      value = std::move(member);
      return true;
    }
    default:
      reader.Fail();
      return false;
  }
}

// One whole message: a union or the registration, encoded on its own.
template <typename T>
std::vector<uint8_t> Encode(const T& message) {
  WireWriter writer;
  Write(writer, message);
  return writer.Take();
}

// One whole message decoded, or nothing when its bytes do not decode or
// run past it.
template <typename T>
std::optional<T> Decode(const uint8_t* data, size_t length) {
  WireReader reader(data, length);
  T message{};
  if (!Read(reader, message) || !reader.ok() || !reader.AtEnd()) return std::nullopt;
  return message;
}

}  // namespace crest::engine

#endif  // CREST_ENGINE_CONTRACT_H_
